### ISSUE TITLE
Gorountines leak

### ISSUE THREAD

**Issue by luannt2909** [elastic/apm-agent-go#1114]
**Describe the bug**
Gorountines leak with apm tracer.
APM version: 	go.elastic.co/apm v1.13.1
First at all, It's appreciated when i applied apm tracer into my project. I also have monitor my service with prometheus (client-prometheus). 
Monitor through Grafana, there're ~30 runtime gorountines in my service initially . However after a while, the runtime gorountines started to further increase into ~1200 goroutines.
I used uber/goleak to detect the cause. And the result as follows:
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 5 in state select, with go.elastic.co/apm.(*Tracer).loop on top of the stack:
goroutine 5 [select]:
go.elastic.co/apm.(*Tracer).loop(0xc000001680)
	/Users/remmy/go/src/my-project/my-service/vendor/go.elastic.co/apm/tracer.go:886 +0x115e
created by go.elastic.co/apm.newTracer
	/Users/remmy/go/src/my-project/my-service/vendor/go.elastic.co/apm/tracer.go:444 +0x86c

 Goroutine 20 in state chan receive, with go.elastic.co/apm.(*Tracer).loop.func2 on top of the stack:
goroutine 20 [chan receive]:
go.elastic.co/apm.(*Tracer).loop.func2(0xc000114540, 0xc0001144e0, 0x47cb0b8, 0xc0002cf000, 0xc000119680, 0xc000001680, 0xc000116630)
	/Users/remmy/go/src/my-project/my-service/vendor/go.elastic.co/apm/tracer.go:789 +0x205
created by go.elastic.co/apm.(*Tracer).loop
	/Users/remmy/go/src/my-project/my-service/vendor/go.elastic.co/apm/tracer.go:786 +0x371

 Goroutine 9 in state select, with go.elastic.co/apm/transport.(*HTTPTransport).WatchConfig.func1 on top of the stack:
goroutine 9 [select]:
go.elastic.co/apm/transport.(*HTTPTransport).WatchConfig.func1(0xc0000960c0, 0x47cb0b8, 0xc0000ae9c0, 0xc000324080, 0xc00002af10, 0x10, 0x0, 0x0)
	/Users/remmy/go/src/my-project/my-service/vendor/go.elastic.co/apm/transport/http.go:384 +0x1a9
created by go.elastic.co/apm/transport.(*HTTPTransport).WatchConfig
	/Users/remmy/go/src/my-project/my-service/vendor/go.elastic.co/apm/transport/http.go:376 +0xae
]
```

**To Reproduce**
My code to initialize APM tracer (use with uber/fx):

```golang
func provideTracer(lifecycle fx.Lifecycle) (*apm.Tracer, error) {
	err := setAPMOsENV()
	if err != nil {
		return nil, err
	}
	apmTransport, err := transport.NewHTTPTransport()
	if err != nil {
		return nil, err
	}
	tracer, err := apm.NewTracerOptions(apm.TracerOptions{Transport: apmTransport})
	if err != nil {
		return nil, err
	}
	lifecycle.Append(
		fx.Hook{
			OnStop: func(c context.Context) error {
				tracer.Close()
				return err
			}})
	return tracer, nil
}
```

```golang
import "go.uber.org/goleak"

func TestMain(t *testing.M) {
	goleak.VerifyTestMain(t)
}
```

**Expected behavior**
How can I resolve this problem? or there are anyway to resolve this?
Thanks so much <3

**Comment by axw** [comment]
> APM version: go.elastic.co/apm v1.13.1

Can you please double check which version you have? The line numbers for v1.13.1 do not match the stack traces you provided, e.g. [tracer.go:886](https://github.com/elastic/apm-agent-go/blob/2045b7b1014e9d7a6c4671d49323a818c488e067/tracer.go#L886) is not a select statement.

> I used uber/goleak to detect the cause. And the result as follows:

The goroutines you listed are likely related to `apm.DefaultTracer`, which is created at package init time and runs a few goroutines. These shouldn't be a problem, but you can eliminated them by calling `apm.DefaultTracer.Close()` if you're not using the default tracer.

> My code to initialize APM tracer (use with uber/fx):

I'm not familiar with uber/fx. If you still think there's a leak, can you please provide a complete program that reproduces the issue?

**Comment by luannt2909** [comment]
Hi @axw ,

> Can you please double check which version you have? The line numbers for v1.13.1 do not match the stack traces you provided, e.g. tracer.go:886 is not a select statement.

About APM version, It's my bad, I provided above versions after upgrading 😭 
It's exactly `go.elastic.co/apm v1.10.0`
> but you can eliminated them by calling apm.DefaultTracer.Close() if you're not using the default tracer.

Yes, I have created new instance Tracer and ignored DefaultTracer, but I missed to call apm.DefaultTracer.Close().

Thanks for reminding me. I'll update my code and report result later.
I would like to close this issue. If It's still leak, I'll reopen later.
Thanks so much.

**Comment by axw** [comment]
Sounds good, thanks!
