### ISSUE TITLE
Can you add parent to transaction which was created by apmEcho?

### ISSUE THREAD

**Issue by Sikarnas** [elastic/apm-agent-go#1119]
Hi,

I'm trying to add distributed tracing to one of go services. I can get traceId from headers, but I don't seem to find a way to add a parent to a current transaction that is created by apmEcho. I can create a new transaction with a parent from traceId, but can I edit transactions which are already started?

I couldn't find this question, sorry if I missed it.

**Comment by axw** [comment]
@Sikarnas in future, please ask questions at https://discuss.elastic.co/c/observability/apm/58. We prefer to use GitHub issues for confirmed bugs and feature requests.

> I can get traceId from headers, but I don't seem to find a way to add a parent to a current transaction that is created by apmEcho. I can create a new transaction with a parent from traceId, but can I edit transactions which are already started?

You cannot update the parent ID of a transaction after it has started.

Can you explain a little more about what you're trying to do? The apmecho instrumentation will extract W3C Trace-Context headers from the incoming request, and use those to set the parent ID.

**Comment by Sikarnas** [comment]
I'm trying to add parent to transaction which is created by apmEcho, but from your comment I see that it does that automatically, but I cannot find anything in apmEcho documentation. How should I name this header, where could I find documentation in regards of parrent Id in headers ?

**Comment by axw** [comment]
> I'm trying to add parent to transaction which is created by apmEcho, but from your comment I see that it does that automatically, but I cannot find anything in apmEcho documentation. How should I name this header, where could I find documentation in regards of parrent Id in headers ?

You can find details here: https://www.elastic.co/guide/en/apm/get-started/current/distributed-tracing.html

The primary header of interest is "traceparent". You should not need to inject it yourself unless you're doing something particularly advanced.

> Mind you, that another service written in Node.js is making a HTTP request to Go service and I want to see the stack traces from both of them, when the parent is txn which has started in Node.js service.

Are you using the Elastic APM Node.js agent? If you are, then it will inject headers into outgoing requests (assuming you're using supported one of the frameworks), and the headers will be automatically picked up by the apmecho instrumentation.

**Comment by Sikarnas** [comment]
> Are you using the Elastic APM Node.js agent?

**Comment by Sikarnas** [comment]
> Are you using the Elastic APM Node.js agent?

**Comment by Sikarnas** [comment]
> Are you using the Elastic APM Node.js agent?
Yes.
> If you are, then it will inject headers into outgoing requests (assuming you're using supported one of the frameworks), and the > headers will be automatically picked up by the apmecho instrumentation.
I didn't know that, I'll test it out, thanks for the help :)
