### ISSUE TITLE
[META 527] User-agent header for transport

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-go#1136]
Implement [514](https://github.com/elastic/apm/pull/514) for all APM agents.

**Comment by axw** [comment]
I think this is going to require breaking changes to our API. Service name and version are properties of the tracer. A transport (which defines the User-Agent) can be shared by multiple tracers. We use `transport.Default` if one is not specified when constructing a tracer, so we can't reasonably update its User-Agent.

I think we'll need to get rid of the `transport.Default` singleton, and always construct one when creating a tracer.
