### ISSUE TITLE
[META 524] OpenTelemetry Bridge

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-go#1140]
Implement https://github.com/elastic/apm/issues/524

**Comment by dmathieu** [comment]
The metrics part of this has shipped in https://github.com/elastic/apm-agent-go/pull/1407
The tracing part is in https://github.com/elastic/apm-agent-go/pull/1410

**Comment by simitt** [comment]
@dmathieu is there anything left on this task, given that the two PRs were merged, and the agent code was even released?

**Comment by dmathieu** [comment]
There shouldn't be, no. I'm closing this issue.
We may have issues we didn't see before, but we'll fix them as we see them.
