### ISSUE TITLE
Update `tracestate` parsing rules to comply with latest W3C spec

### ISSUE THREAD

**Issue by marclop** [elastic/apm-agent-go#1182]
## Description

The latest revision of the W3C trace-context RFC (https://github.com/w3c/trace-context/commit/0c3135d8c2d18f51589098abac94083b3088dcb6) includes some changes state:

```
The test_tracestate_duplicated_keys was broken, it demanded to drop
the whole tracestate when a duplicate key was found. This does not match
what the specification mandates in that situation. Instead,
implementations MAY remove the duplicates from tracestate or even leave
them in as-is.
```

Hence, we need to modify the tracestate validation rules to not drop the tracestate, but rather remove the first instance of a duplicate key when found. https://github.com/elastic/apm-agent-go/blob/7e472e42beb69748652ff672e13b42afbfdfbbcf/tracecontext.go#L272-L274

**Comment by simitt** [comment]
SGTM! This is added as `pending-refinement` - is there anything that needs clarification @marclop ?

**Comment by marclop** [comment]
I forgot to move it to `in progress`, since I was looking at how to addressing this already. It should be in the correct state now
