### ISSUE TITLE
Agent can send empty transaction and span types

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#1211]
**Describe the bug**

`StartTransaction("name", "")` will yield a transaction document without a transaction type field. Similar story for `StartSpan("name", "")`. The UI rightfully expects a non-empty transaction type and span type.

**To Reproduce**
1. Using the agent's API, call `StartTransaction("name", "").End()` and `StartSpan("name", "").End()`
2. Wait for ~15 seconds
3. Check that the transaction and span are visible in the APM UI

**Expected behavior**

A default transaction/span type should be set, so the events are visible in the UI.

**Comment by felixbarny** [comment]
The server might be a better way to fix that as it then covers all agents. But fixing it on both sides doesn't hurt, either.

**Comment by simitt** [comment]
created https://github.com/elastic/apm-server/issues/7376

**Comment by simitt** [comment]
from the [agent spec](https://github.com/elastic/apm/blob/main/specs/agents/tracing-spans.md#transaction-and-span-type-and-subtype-fields):

> If no transaction.type or span.type is provided or the value is an empty string, the agent needs to set a default value custom.
