### ISSUE TITLE
[META 605] Add span links for message tracing

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-go#1222]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F605)](https://github.com/elastic/apm/issues/605)

[![issue details](https://img.shields.io/endpoint?label=spec-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F606)](https://github.com/elastic/apm/issues/606)

Summary of spec changes:

- If your agent instruments any of Azure Service Bus, JMS, Kafka, RabbitMQ, SQS, or SNS, then instrumentation for receiving messages or batches of messages "SHOULD":
    - Create a transaction (with trace-context from message metadata, if any) for the handling of each message, if possible.
    - Otherwise, when creating the transaction or span for the message or batch of messages, look for trace-context in metadata for up to 1000 messages and create a span link for each.
- If your agent supports AWS Lambda instrumentation, then in addition to the creation of span links, this spec change has a number of changes to the context captured for SQS and SNS-triggered invocations. (The special-casing of a message batch with a single message has been dropped.)

**Comment by axw** [comment]
I don't think there's anything to do here for the Go agent at present. We would later, when adding support for other messaging technologies, such as Kafka.

Out of the listed technologies, only SQS and SNS are instrumented. We instrument the AWS SDK for Go, which provides a fairly low level API. Messages can be sent in batch, but not received as a batch AFAICS. Even though messages can be sent as a batch, the Go SDK does not provide any high level API for the batching, so we wouldn't be able to automatically add span links.

**Comment by simitt** [comment]
Thanks for the analysis, closing this issue then in this case. 
cc @AlexanderWert
