### ISSUE TITLE
SQL traces don't catched by agent

### ISSUE THREAD

**Issue by adaosantos** [elastic/apm-agent-go#1237]
**Describe the bug**
Agent don't catch any trace when using GORM, PG or APMSQL modules.

I follow this guide, https://www.elastic.co/pt/blog/how-to-instrument-your-go-app-with-the-elastic-apm-go-agent
I use this compose to provide services https://github.com/deviantony/docker-elk
But any SQL trace is present on APM, only web request is present
<img width="808" alt="image" src="https://user-images.githubusercontent.com/4481171/161114395-db34b3c9-0174-4a82-a208-23cb490b0905.png">

**Comment by axw** [comment]
@adaosantos sorry to hear things aren't working for you. Each of the database libraries you referenced has instrumentation with tests, so we know they do work; we'll need to see your application code to help.

GitHub issues are for confirmed bugs and feature requests -- please open a topic at https://discuss.elastic.co/c/apm and we can follow up on this.
