### ISSUE TITLE
[META 634] a compression-eligible span must not be buffered on an already ended parent

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-go#1242]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/634

**Comment by kruskall** [comment]
I think this is already handled and it was implemented when span compression was introduced: https://github.com/elastic/apm-agent-go/blob/main/span_compressed.go#L157

**Comment by axw** [comment]
Agreed, closing.
