### ISSUE TITLE
Add service_target_* fields to dropped spans metrics

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-agent-go#1291]
Add service_target_type and service_target_name next to destination_service_resource in transaction.dropped_spans_stats array, the related metrics documents should include span.service.target.type and span.service.target.name fields.

See spec for the description and details: 

https://github.com/elastic/apm/blob/main/specs/agents/tracing-spans-service-target.md

**Comment by simitt** [comment]
related https://github.com/elastic/apm-agent-go/pull/1276
