### ISSUE TITLE
Add CPU metrics

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#130]
We should include process (and host?) CPU usage as part of the builtin metrics we report to APM server. Probably use [elastic/gosigar](https://github.com/elastic/gosigar).

**Comment by andrewkroh** [comment]
Also consider using https://github.com/elastic/go-sysinfo. 

We are using it for a few things in Beats, but haven't migrated off of gosigar. I need to update the project's README. To get an idea of what it can collect:

- Linux - https://travis-ci.org/elastic/go-sysinfo/jobs/370385922
- Darwin - https://travis-ci.org/elastic/go-sysinfo/jobs/370385923#L115
- Windows - https://ci.appveyor.com/project/elastic-beats/go-sysinfo/build/21

**Comment by axw** [comment]
Thank you for the pointer, @andrewkroh. Looks good, I'll look into using that first.
