### ISSUE TITLE
Not able to see dependencies in `APM`

### ISSUE THREAD

**Issue by aaqibb13** [elastic/apm-agent-go#1300]
- I've setup `APM` for my Go project and I'm able to traverse  the `errors`, `transactions`, `overview` etc. However, I can't see the project dependencies like I'm able to see with my other service where I'm using the python driver of `elastic-apm`. I'm guessing I'll have to set an `ENV` variable. Any pointers?

- The dependencies should probably look something like this:
![dep](https://user-images.githubusercontent.com/36571725/185382181-aca481ac-eda6-480a-afdc-9d537dd52bce.png)

**Comment by axw** [comment]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions. Provide as much information about your application as you can. e.g. are there any upstream services? Are you using RUM? Which agent version(s) are you using?

If there is a bug, we'll come back and open an issue here.

**Comment by aaqibb13** [comment]
Sure, Thanks!
