### ISSUE TITLE
Child spans of exit spans are silently dropped

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-agent-go#1319]
**Describe the bug**

The agent is silently dropping child spans of exit spans. This is blocking https://github.com/elastic/apm-agent-go/pull/1317 because of trace requests in the apmhttp module being child spans of an exit span.

**Expected behavior**

The spec clarified child spans handling with https://github.com/elastic/apm/pull/433

> Exit spans MUST not have child spans that have a different `type` or `subtype`.

> Exit spans MAY have child spans that have the same `type` and `subtype`.
> For example, an HTTP exit span may have child spans with the `action` `request`, `response`, `connect`, `dns`.
> These spans MUST NOT have any destination context, so that there's no effect on destination metrics.

**Comment by simitt** [comment]
@kruskall we are past the `8.5` milestone, I add it to `8.6` though.
