### ISSUE TITLE
apmhttp superfluous response.WriteHeader call

### ISSUE THREAD

**Issue by PatrykKlimowicz** [elastic/apm-agent-go#1351]
**Describe the bug**
Sporadically I see in the logs this error:

```
2022/11/15 20:14:05 http: superfluous response.WriteHeader call from go.elastic.co/apm/module/apmhttp.(*responseWriter).WriteHeader (handler.go:247)
```
[Link to the code from log](https://github.com/elastic/apm-agent-go/blob/b6f4f158b8f8d8d0c759deb4cd45811439ce70d4/module/apmhttp/handler.go#L247)

**To Reproduce**
I'm using this package for apm: https://pkg.go.dev/go.elastic.co/apm@v1.12.0 

Is it safe to switch to some different apm package to get rid of that behavior? 

**Expected behavior**
No error on writing header is visible.

**Comment by axw** [comment]
@PatrykKlimowicz although the comment points to apmhttp, the responseWriter.WriteHeader method just records the status code and calls the underlying net/http.ResponseWriter's WriteHeader: https://github.com/elastic/apm-agent-go/blob/ab2e73a540c8216d9069b854810a58483841f73b/module/apmhttp/handler.go#L247

Have you confirmed that if you disable the instrumentation, you don't get that error?

**Comment by PatrykKlimowicz** [comment]
> Have you confirmed that if you disable the instrumentation, you don't get that error?

Not sure how I could achieve that. Could you please elaborate more?

**Comment by axw** [comment]
@PatrykKlimowicz a couple of options:

 - temporarily comment out the `apmhttp.Wrap` call from your code
 - set `ELASTIC_APM_TRANSACTION_IGNORE_URLS=*` in your environment

**Comment by PatrykKlimowicz** [comment]
Let me investigate deeper. Thx for your advice!

**Comment by PatrykKlimowicz** [comment]
This could be closed. Poorly written logic behind the request was the issue here. With your advice the error pops up in different place from the app. Solving them one by one fixed the apm "issue". Thx for helping!

**Comment by axw** [comment]
Happy to help, thanks for reporting back.
