### ISSUE TITLE
Add instrumentation for kafka.

### ISSUE THREAD

**Issue by sarabu07** [elastic/apm-agent-go#1375]
Add support for kafka instrumentation for go-lang agent similar to Java and .Net.

**Comment by axw** [comment]
Are you using [sarama](https://pkg.go.dev/github.com/Shopify/sarama), or a difference Kafka client? There is an existing issue for adding instrumentation for Sarama: https://github.com/elastic/apm-agent-go/issues/36

**Comment by axw** [comment]
Closing this as a duplicate of #36. Please reopen with more details if you're using another client.
