### ISSUE TITLE
Add support for pgx v5

### ISSUE THREAD

**Issue by jdvjdv82** [elastic/apm-agent-go#1380]
**Is your feature request related to a problem? Please describe.**
https://github.com/jackc/pgx moved to v5 with trace support via interface
https://github.com/jackc/pgx/blob/master/tracer.go

**Describe the solution you'd like**
either please add support for stdlib like you did for v4 or better pxg v5 natively via prepared interface

**Additional context**
already implemented for xray in here
https://github.com/jackhopner/pgx-xray-tracer

**Comment by axw** [comment]
Support for pgx/v5 was merged last week in https://github.com/elastic/apm-agent-go/pull/1364, and will be in the next release.
