### ISSUE TITLE
apmgormv2 not works

### ISSUE THREAD

**Issue by CaiJinKen** [elastic/apm-agent-go#1403]
**Describe the bug**
apmgormv2 not works with apmgin/v2

**To Reproduce**
env:
ELASTIC_APM_LOG_LEVEL=debug
ELASTIC_APM_SERVER_URL=http://127.0.0.1:8200
ELASTIC_APM_SERVICE_NAME=trace-test-go

1. Use this config 
gin:
```go
import "go.elastic.co/apm/module/apmgin/v2"
import "github.com/gin-gonic/gin"

r:=gin.New()
....
r.Use(apmgin.Middleware(r))

```
gorm:
```go
import mysql "go.elastic.co/apm/module/apmgormv2/v2/driver/mysql"
import "gorm.io/gorm"

db, err := gorm.Open(mysql.Open("user:password(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"), &gorm.Config{})

....

```
handler:
```go
func Do(ctx *gin.Context) {
....
var user User
db.WithContext(ctx).Find(&user)
....
ctx.Json(200, user)
}

```

3. add a router path to gin, and the handler access mysql with db
4. access the path, and get the user info
5. access the trace-test-go service on kibana apm module, we can find the access path
6. the transactions shows gin router only, has no sql info
<img width="1680" alt="截屏2023-03-26 21 42 24" src="https://user-images.githubusercontent.com/36183188/227779798-803bb701-0919-46ab-9730-e79a86a58674.png">

**Expected behavior**
kibana apm has mysql trace info follows gin path

**Comment by axw** [comment]
Try replacing

`db.WithContext(ctx)`

with

`db.WithContext(ctx.Request.Context())`

**Comment by CaiJinKen** [comment]
Yes, i has read the apmgin docs very carefully, shows `For each request, a transaction is stored in the request context, which can be obtained via [gin.Context](https://godoc.org/github.com/gin-gonic/gin#Context).Request.Context() in your handler.`. 
Thasks a lot!
