### ISSUE TITLE
Implement order of precedence for configuration

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-go#145]
As per https://github.com/elastic/apm-agent-nodejs/issues/287

**Comment by axw** [comment]
The Go agent doesn't currently support a config file. If we add one, I'll make sure this ordering followed. As it stands, the Go agent has support for:
 - environment variables
 - default values

*After* a tracer is constructed, you can then change the configuration with various setter methods. I don't consider this to be equivalent to "in-line configuration", as it's not at construction time; it's instead a very deliberate decision to change the configuration.

Closing this, as there's nothing to do.

**Comment by alvarolobato** [comment]
Thanks
