### ISSUE TITLE
Update doc with go support policy

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-agent-go#1485]
**Describe the bug**

The document requirements are really oudated and bit misleading (we're not really testing with 1.8)

**To Reproduce**
Open https://github.com/elastic/apm-agent-go/blob/main/docs/set-up.asciidoc#requirements

**Expected behavior**
Updated policy

**Comment by dmathieu** [comment]
Isn't the doc auto-updated when a release is triggered?

**Comment by simitt** [comment]
While on it, please also align the release notes for the latest release
- https://www.elastic.co/guide/en/apm/agent/go/current/release-notes-2.x.html
vs 
- https://github.com/elastic/apm-agent-go/releases/tag/v2.4.3
