### ISSUE TITLE
Metrics: GC metrics don't line up with Metricbeat

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#153]
See https://github.com/elastic/apm-agent-go/pull/151#pullrequestreview-139645844

**Comment by axw** [comment]
https://github.com/elastic/beats/issues/7785 explains why cpu_fraction doesn't match up. Metricbeat has it down as "long", and we don't have a mapping for it at all at the moment.

**Comment by axw** [comment]
The summary metrics from metricbeat (golang.heap.gc.pause.*) reset between collections, and values may be missed.

For the first cut, I'd rather focus on the monotonically increasing values and calculate moving averages and such.

Later if/when percentile rollup aggregations are possible, we can look into supplying the period-specific summaries.

**Comment by graphaelli** [comment]
Thanks for tracking down `cpu_fraction` - we don't have any mappings for gc metrics - should we?

Agreed on keeping no state for now.  I should have mentioned elastic/beats#6543 when I opened this - the missing values are known to beats but we haven't spent time on a fix yet.

**Comment by axw** [comment]
> Thanks for tracking down cpu_fraction - we don't have any mappings for gc metrics - should we?

Yes, I think so.

> Agreed on keeping no state for now. I should have mentioned elastic/beats#6543 when I opened this - the missing values are known to beats but we haven't spent time on a fix yet.

That particular issue wouldn't affect the agent, since it's in the same process. Nevertheless, will leave it out and we can later come to a solution that works for both.
