### ISSUE TITLE
Support for Redis v9

### ISSUE THREAD

**Issue by mymmrac** [elastic/apm-agent-go#1576]
Are there any plans to support Redis v9? It was released more than a year ago (https://github.com/redis/go-redis/releases/tag/v9.0.0) and v8 no longer supported

Currently, APM only has module for Redis v8

**Comment by dmathieu** [comment]
See https://github.com/elastic/apm-agent-go/pull/1413

**Comment by mymmrac** [comment]
Got it, thanks!
