### ISSUE TITLE
defer c.finishSpan(ctx, span, resultError)  will not capture error 

### ISSUE THREAD

**Issue by kaka19ace** [elastic/apm-agent-go#159]
Hi, i find a bug when debug the apmsql,  

https://github.com/elastic/apm-agent-go/blob/master/module/apmsql/conn.go
defer c.finishSpan(ctx, span, resultError)  just pass nil value ahead of time.

maybe using closure will solve it:
defer func() {c.finishSpan(ctx, span, resultError) }()

**Comment by axw** [comment]
Ouch! Thanks very much for reporting the bug, I'll fix it and add a test case.

**Comment by kaka19ace** [comment]
hi,  error is interface type,  passing pointer to the function may be not a proper way

**Comment by axw** [comment]
> hi, error is interface type, passing pointer to the function may be not a proper way

There's no problem with taking the address of an error or interface variable. There's a new test case that shows that this works.

A closure would also work, but internally it works by storing the address of the variable being closed over, and dereferencing it inside the closure. Same effect, just slightly more verbose.
