### ISSUE TITLE
Empties queries with microsoft/mssqldb package

### ISSUE THREAD

**Issue by dmathieu** [elastic/apm-agent-go#1594]
Hello guys, thank you for the switch to microsoft package!
There might be an issue btw, I am not able to perform a SELECT Id FROM Table WHERE Id = **$1** ; I get a no rows returned from row.Scan.
Actually I am able to retrieve rows using the formatted query:
```
// NOK
	query := "SELECT Id FROM Customer WHERE Id = $1"
	var customer Customer
	row := db.QueryRowContext(apm.ContextWithTransaction(context.Background(), tx), query, 2)
// OK
	query := fmt.Sprintf("SELECT Id FROM Customer WHERE Id = %d", 2)
	var customer Customer
	row := db.QueryRowContext(apm.ContextWithTransaction(context.Background(), tx), query)
```
Here is how I init my db instance:
```
package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"

	"github.com/sirupsen/logrus"
	"go.elastic.co/apm/module/apmsql/v2"
	_ "go.elastic.co/apm/module/apmsql/v2/sqlserver"
	"go.elastic.co/apm/v2"
)

func main() {
	settings, err := LoadSettings("server.conf.json")
	dsn := settings.Database.String("go-test")
	db, err := apmsql.Open("sqlserver", dsn)
	if err != nil {
		logrus.StandardLogger().Fatal(err)
	}
	defer db.Close()
```

_Originally posted by @thibleroy in https://github.com/elastic/apm-agent-go/issues/1569#issuecomment-1999297431_

**Comment by dmathieu** [comment]
Thank you for reporting this @thibleroy. Your code sample is a bit too short to be something reproducible.
Would you be able to setup a short working example?

Does it work without the apmsql package?

**Comment by thibleroy** [comment]
I can explain the issue we faced now. We were connecting using the mssql:// prefix in the DSN. However, to use the apmsql package, we must use the sqlserver:// prefix, right? Here is the explanation: [Microsoft go-mssqldb README](https://github.com/microsoft/go-mssqldb?tab=readme-ov-file#query-parameter-token-replace-driver-mssql). Therefore, I believe we should close this issue, as it pertains to the MSSQL driver and its usage.
