### ISSUE TITLE
`host.name` assigned with `pod.name`

### ISSUE THREAD

**Issue by crespocarlos** [elastic/apm-agent-go#1636]
## Describe the bug

When viewing the Hosts UI with Go APM service active in a k8s pod, Go agent monitored services report the pod name in the `host.name`, which makes the Hosts View display hosts that do not correlate with hosts monitored by the system integration.

## Steps to reproduce
- Run a Go APM instrumented service in a k8s pod
- Ingest that into ES
- Open the Infra UI

edge-oblt can be used for the above.

## Expected behavior

Only hosts (VMs) are expected to be present in the Hosts View.

## Additional context

<img width="600px" alt="image" src="https://github.com/user-attachments/assets/085df402-884a-4ee9-bc87-d552175f6943">

<img width="600px" alt="image" src="https://github.com/user-attachments/assets/49884273-4877-4f74-94ba-ff4ad3a2b052">

<img width="600px" alt="image" src="https://github.com/user-attachments/assets/2706999a-831f-4e05-97ee-46162ad82aa7">

<img width="600px" alt="image" src="https://github.com/user-attachments/assets/fa3b5775-6b0c-457e-a0e8-961e929e328f">

Sample doc

```
{
  "_index": ".ds-metrics-apm.internal-default-2024.07.10-000004",
  "_id": "n6S5wJABi-i5Y9bCcNyn",
  "_score": 0,
  "_source": {
    "agent": {
      "name": "go",
      "version": "2.6.0"
    },
    "cloud": {
      "availability_zone": "us-central1-c",
      "instance": {
        "id": "5320670725633961051",
        "name": "gke-edge-oblt-edge-oblt-pool-8fc2868f-9w9b"
      },
      "machine": {
        "type": "e2-highcpu-4"
      },
      "project": {
        "id": "elastic-observability"
      },
      "provider": "gcp",
      "region": "us-central1"
    },
    "data_stream": {
      "dataset": "apm.internal",
      "namespace": "default",
      "type": "metrics"
    },
    "host": {
      "architecture": "amd64",
      "hostname": "opbeans-go-66d4d66948-288rd",
      "ip": "35.225.250.101",
      "name": "opbeans-go-66d4d66948-288rd",
      "os": {
        "platform": "linux"
      }
    },
    "metricset": {
      "name": "span_breakdown"
    }
  }
}
{
  "_index": ".ds-metrics-apm.internal-default-2024.06.19-000001",
  "_id": "fhKOVJAB-A68Bg7Z5cK5",
  "_score": 0,
  "_source": {
    "agent": {
      "name": "go",
      "version": "2.6.0"
    },
    "cloud": {
      "availability_zone": "us-central1-c",
      "instance": {
        "id": "5587317589758934282",
        "name": "gke-edge-oblt-edge-oblt-pool-8fc2868f-95sb"
      },
      "machine": {
        "type": "e2-highcpu-4"
      },
      "project": {
        "id": "elastic-observability"
      },
      "provider": "gcp",
      "region": "us-central1"
    },
    "data_stream": {
      "dataset": "apm.internal",
      "namespace": "default",
      "type": "metrics"
    },
    "host": {
      "architecture": "amd64",
      "hostname": "auditbeat-7zqt2",
      "ip": "35.239.183.88",
      "name": "auditbeat-7zqt2",
      "os": {
        "platform": "linux"
      }
    },
    "metricset": {
      "name": "span_breakdown"
    }
  }
}
```

**Comment by dmathieu** [comment]
I'm not seeing anything that sets `host.name` within this agent's codebase. Could that be set elsewhere?

**Comment by crespocarlos** [comment]
I found one service that's sending the right host name:

<img width="1465" alt="image" src="https://github.com/user-attachments/assets/e344e9f3-78fc-46b1-8d83-0d0e28e930d3">


```
{
  "_index": ".ds-metrics-apm.internal-default-2024.06.19-000001",
  "_id": "rMuOVJABJL0PvM5Y3DhL",
  "_score": 0,
  "_source": {
    "agent": {
      "name": "go",
      "version": "2.6.0"
    },
    "cloud": {
      "availability_zone": "us-central1-c",
      "instance": {
        "id": "6794187993886623003",
        "name": "gke-edge-oblt-edge-oblt-pool-8fc2868f-vxjm"
      },
      "machine": {
        "type": "e2-highcpu-4"
      },
      "project": {
        "id": "elastic-observability"
      },
      "provider": "gcp",
      "region": "us-central1"
    },
    "data_stream": {
      "dataset": "apm.internal",
      "namespace": "default",
      "type": "metrics"
    },
    "host": {
      "architecture": "amd64",
      "hostname": "gke-edge-oblt-edge-oblt-pool-8fc2868f-vxjm",
      "ip": "34.45.234.162",
      "name": "gke-edge-oblt-edge-oblt-pool-8fc2868f-vxjm",
      "os": {
        "platform": "linux"
      }
    },
    "metricset": {
      "name": "app"
    },
    "service": {
      "environment": "production",
      "language": {
        "name": "go",
        "version": "go1.21.11"
      },
      "name": "packetbeat",
      "node": {
        "name": "gke-edge-oblt-edge-oblt-pool-8fc2868f-vxjm"
      },
      "runtime": {
        "name": "gc",
        "version": "go1.21.11"
      },
      "version": "8.15.0"
    }
  }
}
```

**Comment by crespocarlos** [comment]
The same node is running auditbeat and packetbeat. packetbeat reports the correct host name, auditbeat doesn't. I can't find what is different between the two that causes this. Both are running the same go agent version

**Comment by simitt** [comment]
The go agent doesn't set the `host.name`, it sends a configured or detected name and then the apm-server has an algorithm to derive `host.name` depending on various factors, as described in https://github.com/elastic/apm-server/issues/8118#issue-1238158231.

https://www.elastic.co/guide/en/apm/agent/go/current/configuration.html#config-hostname describes how a host name can be configured via the go agent. You'll need to check the setup of the instrumented services as to which configurations they have set.

**Comment by crespocarlos** [comment]
I had a quick call with @Mpdreamz , and he explained that the non-matching host names shipped by APM agents are due to missing configuration as exemplified in this comment https://github.com/elastic/observability-dev/issues/3321#issuecomment-2236909682.
