### ISSUE TITLE
apm.TransactionFromContext always nil

### ISSUE THREAD

**Issue by ga845937** [elastic/apm-agent-go#1637]
**Describe the bug**
I am using a combination of:
go.elastic.co/apm v1.15.0
go.elastic.co/apm/module/apmgin/v2 v2.6.0
go.elastic.co/apm/module/apmsql/v2 v2.6.0

apmgin and apmsql work
![image](https://github.com/user-attachments/assets/1f9bb192-12a6-4ce1-bf6d-12feae69638a)

**To Reproduce**

gin middleware setting
```
engine := gin.New()
engine.Use(apmgin.Middleware(engine), middleware.Logger())
```

I try to get TraceID in middleware.Logger(), 
[Elastic Docs](https://www.elastic.co/guide/en/apm/agent/go/current/builtin-modules.html#builtin-modules-apmgin) module/apmgin say [ For each request, a transaction is stored in the request context, which can be obtained via gin.Context.Request.Context() in your handler. ]

so in middleware.Logger()
```
var traceID string
tx := apm.TransactionFromContext(context.Request.Context())
if tx != nil {
    traceID = tx.TraceContext().Trace.String()
}

logger.Info( "request",
    zap.String("traceID", traceID),
    .... other field
)
```

tx always nil, so traceID always ""

**Expected behavior**
get the traceID

**Comment by axw** [comment]
> I am using a combination of:
> go.elastic.co/apm v1.15.0
> go.elastic.co/apm/module/apmgin/v2 v2.6.0
> go.elastic.co/apm/module/apmsql/v2 v2.6.0

Using a combination of v1 and v2 is not going to work - you will need to update from apm to apm/v2.
