### ISSUE TITLE
Support for confluent-kafka-go

### ISSUE THREAD

**Issue by heisGarvit** [elastic/apm-agent-go#1638]
**Is your feature request related to a problem? Please describe.**
There is no support for instrumenting [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go)

**Describe the solution you'd like**
Is there a plan to add support for confluent-kafka-go on Elastic APM Go Agent ?
If not, I wish to [contribute](https://github.com/elastic/apm-agent-go/blob/main/CONTRIBUTING.md)

**Describe alternatives you've considered**
There is Opentelemetry instrumentation by [splunk](https://github.com/signalfx/splunk-otel-go/tree/main/instrumentation/github.com/confluentinc/confluent-kafka-go/v2/kafka/splunkkafka)

**Additional context**
I did ask on [discuss](https://discuss.elastic.co/t/elastic-apm-go-agent-support-for-confluent-kafka-go/363464) but no one reverted, If no one else is working on it or there are no plans yet, may I start writing code for it ? will the Pull request be considered for merge?

**Comment by dmathieu** [comment]
This library is in "maintenance mode" (see the top of the [README](https://github.com/elastic/apm-agent-go/blob/main/README.md)), meaning it only gets bug and security fixes, no new features.
Our recommendation is to migrate to OpenTelemetry (we provide a [bridge](https://www.elastic.co/guide/en/apm/agent/go/current/opentelemetry.html) that can help you transition).
