### ISSUE TITLE
[META 882] Check classic and OTel agents against serverless

### ISSUE THREAD

**Issue by obltmachine** [elastic/apm-agent-go#1640]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/882
- Spec issue: https://github.com/elastic/apm/issues/883

**Comment by dmathieu** [comment]
I ran a simple app instrumented with the APM client and configured to send its data to a serverless project.

```golang
package main

import (
	"io"
	"log"
	"net/http"

	"go.elastic.co/apm/module/apmhttp/v2"
	_ "go.elastic.co/apm/v2"
)

func main() {
	handler := http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		_, _ = io.WriteString(w, "Hello, world!\n")
	})

	http.Handle("/hello", apmhttp.Wrap(handler))
	err := http.ListenAndServe(":7777", nil)
	if err != nil {
		log.Fatal(err)
	}
}
```
<img width="1448" alt="Screenshot 2024-07-31 at 10 00 37" src="https://github.com/user-attachments/assets/0be0a486-50ab-4726-a87e-e6b563855f8b">

<img width="1462" alt="Screenshot 2024-07-31 at 10 00 57" src="https://github.com/user-attachments/assets/9cf37139-e685-45fb-8406-c90834cf260c">

**Comment by dmathieu** [comment]
I ran the [otel-collector](https://github.com/open-telemetry/opentelemetry-go/tree/main/example/otel-collector) example from otel-go, configured to send its data through OTLP HTTP to a serverless project.

<img width="1452" alt="Screenshot 2024-07-31 at 10 19 48" src="https://github.com/user-attachments/assets/36599710-276a-4b52-b1c3-a9259375f65e">
<img width="1443" alt="Screenshot 2024-07-31 at 10 20 12" src="https://github.com/user-attachments/assets/ee5269a3-1bf1-4a10-84a8-78ce1c0c4bbd">
