### ISSUE TITLE
Using Elastic APM with GORM?

### ISSUE THREAD

**Issue by nallown** [elastic/apm-agent-go#168]
I'm using a GORM (a orm) with my Go server and I need your guys help to find how I can use it with **apmsql**.

In the docs they said I just need to import their gorm library which is a wrapper around the normal sql database and I can't figure out how to make GORM use the custom MySQL db instance from **apmsql**.

Do you have any idea how I can make GORM use the db instance ([which you can find here](http://gorm.io/docs/connecting_to_the_database.html#MySQL)) from **apmsql** instead of the default MySQL one?

Normally I just have to do:
```go
import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"github.com/jinzhu/gorm"
)

func main() {
	db, err := gorm.Open("mysql", "user:password@/dbname?charset=utf8&parseTime=True&loc=Local")
}
```

I tried using the code below and it gave me [this error](https://github.com/jinzhu/gorm/issues/2012#issuecomment-408997905).
```go
import (
	"github.com/elastic/apm-agent-go/module/apmsql"
	_ "github.com/elastic/apm-agent-go/module/apmsql/mysql"
	"github.com/jinzhu/gorm"
)

func main() {
	db, err := gorm.Open(apmsql.DriverPrefix+"mysql", "user:password@/dbname?charset=utf8&parseTime=True&loc=Local")
}
```

**Comment by axw** [comment]
@Azuka thank you. I'll look into formalising this into a module some time soon.

**Comment by nallown** [comment]
Thank you both, you're doing a great job contributing to other people's issues. You're much better then some other.

**Comment by axw** [comment]
@nallown do you have everything you need now? OK to close this one now? I've opened #169 to track creating a module for gorm.

**Comment by nallown** [comment]
@axw all good man thanks for your input, I'll close the issue
