### ISSUE TITLE
apmecho: Add support for labstack/echo lite web framework

### ISSUE THREAD

**Issue by rv-rsouza** [elastic/apm-agent-go#20]
Please add support for [/labstack/echo](/labstack/echo) lite web framework to contrib modules.

**Comment by axw** [comment]
@rv-rsouza looks straight forward. I'll take a look soon, if nobody else (you?) gets to it first.

**Comment by axw** [comment]
@rv-rsouza I've just merged support for Echo. As I mentioned on the PR, the middleware doesn't currently capture the request body. If you need that, I'd be happy to review any PRs.

**Comment by rv-rsouza** [comment]
Wonderful!

In case you really need that, you can use something like:

```go
// middleware definition
// func(next echo.HandlerFunc) echo.HandlerFunc {
// ...
res := c.Response()
resBody := new(bytes.Buffer)

mw := io.MultiWriter(res.Writer, resBody)
writer := &bodyResponseWriter{Writer: mw, ResponseWriter: res.Writer}

res.Writer = writer

// call the other handlers in the chain to fill in the response
err = next(c)
if err != nil {
	return err
}

// at this point resBody has the response body
```
