### ISSUE TITLE
Can't fetch howett.net/plist

### ISSUE THREAD

**Issue by rluisr** [elastic/apm-agent-go#218]
**Describe the bug**
Glide can't get dependencies `howett.net/plist`.
```
[INFO]  --> Fetching howett.net/plist
[WARN]  Unable to checkout howett.net/plist
[ERROR] Error looking for howett.net/plist: Unable to get repository
```
*Glide.yaml*
```
- package: github.com/elastic/apm-agent-go
  version: ^0.5.1
```

**Comment by axw** [comment]
@rluisr thanks for reporting the issue.

To assist me in trying to reproduce the issue:

- What version of glide are you using?
- What commands are you running?

I don't use glide normally, but I've just install glide v0.13.1, initialised a glide.yaml and added howett.net/plist, and then ran "glide install". It all worked for me.

Have you already ruled out intermittent network issues?

**Comment by rluisr** [comment]
Thanks reply.

> What version of glide are you using?

0.13.0-dev

> What commands are you running?

`glide up`

I'm facing this issue via dep too.
don't know this related with this issue, `howett.net`'s A record is changed on `2018-09-04`
```
192.154.110.147 | Los Angeles - United States | GorillaServers, Inc. | 2018-09-03
```

**Comment by axw** [comment]
I'm kind of guessing here, but I think the package may have previously been hosted on github (https://github.com/DHowett/go-plist), and is now hosted on gitlab (https://gitlab.howett.net/go/plist). The vanity domain points at gitlab:

```
<!DOCTYPE HTML>                                                                                  
<html>                                                                                           
<head>                                                                                           
        <meta http-equiv="content-type" content="text/html; charset=utf-8">                      
                                                                                                 
        <title>Package plist</title>                                                             
        <meta name="go-import" content="howett.net/plist git https://gitlab.howett.net/go/plist">
</head>                                                                                          
<body>                                                                                           
This exists solely for the purposes of go-get. Go, get out, git.                                 
</body>                                                                                          
</html>                                                                                          
```

Do you have a firewall configured that is preventing access to gitlab? Seems strange that both glide and dep are failing.
