### ISSUE TITLE
undefined: mux.MiddlewareFunc

### ISSUE THREAD

**Issue by sharanraj124** [elastic/apm-agent-go#232]
@axw 
```
import (
        "github.com/gorilla/mux"
	"github.com/elastic/apm-agent-go"
	"github.com/elastic/apm-agent-go/module/apmgorilla"
)
```
I getting this type of error.
Users/appleapple/go/src/github.com/elastic/apm-agent-go/module/apmgorilla/middleware.go:21:30:  `undefined: mux.MiddlewareFunc`

**Comment by axw** [comment]
You will need to update gorilla/mux. MiddlewareFunc was added recently. Please see https://www.elastic.co/guide/en/apm/agent/go/current/supported-tech.html#_gorilla_mux.

**Comment by sharanraj124** [comment]
I am using new gorilla/mux version `v1.6.2`. but continously showing this error. `undefined: mux.MiddlewareFunc`

**Comment by axw** [comment]
@sharanraj124 you can see the MiddlewareFunc type defined here, at v1.6.2: https://github.com/gorilla/mux/blob/v1.6.2/middleware.go#L11

We also build/test all of the agent packages with the latest dependencies on every PR, and periodically: https://travis-ci.org/elastic/apm-agent-go.

There's something wrong with your dependencies. Perhaps you have an older version of gorilla/mux vendored?

**Comment by sharanraj124** [comment]
thanks @axw  this is working
