### ISSUE TITLE
docs: add glossary of terms

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#239]
Define "transaction", "span", "instrumentation", etc. Perhaps to be shared by all agents?

**Comment by bmorelli25** [comment]
I definitely think this is necessary. I think it makes sense for the glossary to live in the [APM Overview](https://www.elastic.co/guide/en/apm/get-started/current/index.html) docs. I'm going to open a new issue in `apm` if you're on board with that.

**Comment by axw** [comment]
Thanks @bmorelli25, I'll close this one.
