### ISSUE TITLE
APM server reject requests when client ELASTIC_APM_DISTRIBUTED_TRACING=true 

### ISSUE THREAD

**Issue by raminrahbari** [elastic/apm-agent-go#245]
APM Server validation schema expect id to have "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$" when ELASTIC_APM_DISTRIBUTED_TRACING is "true", it causes APM server to reject the request. Seems like the APM server still expecting UUID pattern.

**Comment by axw** [comment]
ELASTIC_APM_DISTRIBUTED_TRACING was added for development purposes, and won't work without a custom server.

The v2 branch has all of the changes required for distributed tracing, which will go into the next major release. The v2 agent branch requires the v2 server branch.

**Comment by Azuka** [comment]
Thanks for clarifying, @axw. Where can I find information on when the two will be released (both agent and server support)?

**Comment by axw** [comment]
> Thanks for clarifying, @axw. Where can I find information on when the two will be released (both agent and server support)?

Because releases can slip, I can't provide a date. The Go agent and the server are both functional. Work is ongoing on the UI, and the other agents are a mix. It shouldn't be too far away.
