### ISSUE TITLE
gocraft/dbr over MySQL and net/http client Supported or any Workaround?

### ISSUE THREAD

**Issue by zhongdj** [elastic/apm-agent-go#305]
Currently we have a Gin + MySQL + Reids + CephFS + Http Client application, I want to use elastic apm suite to understand the application performance, in the past 4 days, we tried on apm-go-agent, apmsql(dbr over mysql), apmhttp (as client), currently it is not successful. *(https://www.elastic.co/blog/elastic-apm-agent-go-beta-released)

Gin module works fine, we can get all HTTP Server API without a problem.
But when we start using gocraft/dbr lib, we cannot find any place to replace 'sql.Register', and it turned out there is no 'span' under timeline panel.

Since our application works as http client as well, so there many http call out, it seems that apm-go-agent supports by WrapClient and other code as following:

```
       import (
         ...
	 "github.com/elastic/apm-agent-go"
	 "github.com/elastic/apm-agent-go/module/apmhttp"
       )
       ...
	tx := elasticapm.DefaultTracer.StartTransaction(method + " " +path, "request")
	ctx = elasticapm.ContextWithTransaction(context.Background(), tx)
	req = req.WithContext(ctx)
	cli.client = apmhttp.WrapClient(cli.client)
```

It's not working, is there any quick fix or guideline to fix it?

**Comment by axw** [comment]
> But when we start using gocraft/dbr lib, we cannot find any place to replace 'sql.Register', and it turned out there is no 'span' under timeline panel.

You won't be able to use `dbr.Open`, but you can instead construct a `dbr.Connection` with an instrumented `sql.DB` like this:

```go
import (
    "github.com/elastic/apm-agent-go/module/apmsql"
    _ "github.com/elastic/apm-agent-go/module/apmsql/mysql"
)

func main() {
    sqlConn, _ := apmsql.Open("mysql", "...")
    conn := &dbr.Connection{
        DB:            sqlConn, // <- underlying database/sql.DB is instrumented
        EventReceiver: &dbr.NullEventReceiver{},
        Dialect:       dialect.MySQL,
    }
}
```

You will need to use the Context methods (LoadContext, ExecContext, etc.), and pass in the surrounding request context, similar to how I show for outgoing HTTP requests below.

> Since our application works as http client as well, so there many http call out, it seems that apm-go-agent supports by WrapClient and other code as following:

How are you using cli.client? One thing you'll have to do is propagate the incoming request context, so for example in a Gin handler you would do something like this:

```go
var client = apmhttp.WrapClient(http.DefaultClient)

func ginHandler(c *gin.Context) {                                             
    req, _ := http.NewRequest("GET", "http://example.com", nil)
    resp, err := client.Do(req.WithContext(c.Request.Context())) // <- propagate incoming request context
    ...
})                                                                            
```

**Comment by zhongdj** [comment]
Thx axw. I followed the sql part as following, but we came across error ```runtime error: invalid memory address or nil pointer dereference``` while using the ```conn *dbr.Connection``` inside ```NewSession``` method

```
import (
	...
	_ "github.com/go-sql-driver/mysql"
	   "github.com/elastic/apm-agent-go/module/apmsql"
        _ "github.com/elastic/apm-agent-go/module/apmsql/mysql"
)
...
var ServerConnection *dbr.Connection

func init() {
    ...
    sqlConn, err := apmsql.Open("mysql", dsn)
    ServerConnection := &dbr.Connection{
        DB:            sqlConn, // <- underlying database/sql.DB is instrumented
        EventReceiver: serverDbReceiver,
        Dialect:       dialect.MySQL,
    }
    ...
}

   ...
func GetSession() *dbr.Session {
	return ServerConnection.NewSession(nil)
}
```
and dbr.go's NewSession is as following:
```
func (conn *Connection) NewSession(log EventReceiver) *Session {
	if log == nil {
		log = conn.EventReceiver // <---- IT crashes HERE
	}
	return &Session{Connection: conn, EventReceiver: log}
}
```

**Comment by axw** [comment]
> Thx axw. I followed the sql part as following, but we came across error runtime error: invalid memory address or nil pointer dereference while using the conn *dbr.Connection inside NewSession method

This looks like a problem with how you're initialising ServerConnection. That line in NewSession would only panic if ServerConnection is nil.

I assume the code snippet you've supplied is not exactly 1:1 with your codebase, but if you're really doing this:

```go
ServerConnection := &dbr.Connection{
```

then you're not assigning to the global `ServerConnection` variable. You should change it to

```go
ServerConnection = &dbr.Connection{
```

(i.e. remove the ':')

**Comment by zhongdj** [comment]
Thx axw. after remove the : then the code works. but the sql span still not showing up.

I enabled elastic apm debugged flag. then I found 
```
{
            ID: model.TransactionID{
                SpanID: {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
                UUID:   {0xda, 0x70, 0xc9, 0xe4, 0x4e, 0x3b, 0x83, 0x28, 0x96, 0x4b, 0x15, 0xf3, 0x91, 0xf5, 0x82, 0x9a},
            },
            TraceID:   {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
            ParentID:  {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
            Name:      "POST /api/v1/trace/log",
            Type:      "request",
            Timestamp: model.Time{
                wall: 0x36cd1d20,
                ext:  63677237857,
                loc:  (*time.Location)(nil),
            },
            Duration: 0.16301400000000002,
            Result:   "HTTP 2xx",
            Context:  &model.Context{
                Request: &model.Request{
                    URL:         model.URL{Full:"", Protocol:"http", Hostname:"xxx.com", Port:"8090", Path:"/api/v1/trace/log", Search:"", Hash:""},
                    Method:      "POST",
                    Headers:     &model.RequestHeaders{ContentType:"application/x-www-form-urlencoded", Cookie:"__hash__cache=b36c7c5d-9db0-47be-a860-9e42054af01a", UserAgent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"},
                    Body:        (*model.RequestBody)(nil),
                    HTTPVersion: "1.1",
                    Cookies:     {
                        &http.Cookie{
                            Name:       "__hash__cache",
                            Value:      "b36c7c5d-9db0-47be-a860-9e42054af01a",
                            Path:       "",
                            Domain:     "",
                            Expires:    time.Time{},
                            RawExpires: "",
                            MaxAge:     0,
                            Secure:     false,
                            HttpOnly:   false,
                            SameSite:   0,
                            Raw:        "",
                            Unparsed:   nil,
                        },
                        
                    },
                    Env:    {},
                    Socket: &model.RequestSocket{Encrypted:false, RemoteAddress:"127.0.0.1"},
                },
                Response: &model.Response{
                    StatusCode:  200,
                    Headers:     &model.ResponseHeaders{ContentType:"application/json; charset=utf-8"},
                    HeadersSent: &bool(true),
                    Finished:    &bool(true),
                },
                User:   (*model.User)(nil),
                Custom: {
                    {
                        Key:   "gin",
                        Value: apmgin.ginContext{Handler:".../server/controllers/session.WriteLog"},
                    },
                },
                Tags: {},
            },
            Sampled:   (*bool)(nil),
            SpanCount: model.SpanCount{},
            Spans:     nil,
        },
    },
}
```

It seemed that transaction is not Sampled and there is no Spans. I am curious is there any special configuration to enable Sampled?

**Comment by axw** [comment]
> It seemed that transaction is not Sampled and there is no Spans. I am curious is there any special configuration to enable Sampled?

Sampled being nil is not an issue -- its default value is true. It is an issue that there are no spans, though.

Are you using the context methods for database queries? And are you passing in the request context? This is necessary to add database query spans to the web transaction.

In your handler, you should be doing something like this:

```go
func ginHandler(c *gin.Context) {
    session := GetSession()
    session.Select("column").From("table").LoadContext(c.Request.Context(), &result)
})
```

**Comment by zhongdj** [comment]
Thx axw. After struggling with our code structure, HTTP Client part works. Our lovely programmer uses context.Context.TODO() other than gin's Request.Context(), so it does not work. After replacing it with gin's Request.Context(), the beautiful Spans showing up.

I need to go back to fight with those sql stuff, and will feedback after a while.

**Comment by axw** [comment]
> Thx axw. After struggling with our code structure, HTTP Client part works. Our lovely programmer uses context.Context.TODO() other than gin's Request.Context(), so it does not work. After replacing it with gin's Request.Context(), the beautiful Spans showing up.

Great to hear!

> I need to go back to fight with those sql stuff, and will feedback after a while.

Looking forward to your feedback.

**Comment by zhongdj** [comment]
Thx axw. sql part works as well.

**Comment by axw** [comment]
> Thx axw. sql part works as well.

Brilliant.

If you have any suggestions about making this easier (i.e. what could we do to avoid this issue?), I'd appreciate any suggestions you/your team have - either in the form of issues, or as a discussion in our forum at https://discuss.elastic.co/c/apm.
