### ISSUE TITLE
[APM-CI][Go] Add W3C Trace Context validation stage to pipeline

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#337]
Our Travis CI tests currently run the w3c/trace-context test harness against the Go agent using docker-compose. We should do this in Jenkins, for completeness.

**Comment by v1v** [comment]
IIUC, this particular requirement has been solved in https://github.com/elastic/apm-agent-go/pull/588

I see an entry in the log output to validate it does run that particular test harness
```
[2019-10-16T01:46:39.711Z] W3C Distributed Tracing Validation
...
[2019-10-16T01:51:58.353Z] Creating apm-agent-go-testing_trace-context-harness_1 ... 
....
```

Can we close it?

**Comment by axw** [comment]
Yes indeed, thanks @v1v
