### ISSUE TITLE
cmd: go get -u apmhttp failed

### ISSUE THREAD

**Issue by EDDYCJY** [elastic/apm-agent-go#400]
**Describe the bug**
Pulling apmhttp package failed.

**To Reproduce**

```
$ go get -u github.com/elastic/apm-agent-go/module/apmhttp
github.com/elastic/apm-agent-go/module/apmhttp/ignorer.go:8:2: use of internal package go.elastic.co/apm/internal/apmconfig not allowed
github.com/elastic/apm-agent-go/module/apmhttp/ignorer.go:9:2: use of internal package go.elastic.co/apm/internal/wildcard not allowed
```

**Expected behavior**
I hope to pull apmhttp package correctly.

**Comment by axw** [comment]
@EDDYCJY apologies for the slow response, I have been away on holidays. I presume you figured out that the correct import path is `go.elastic.co/apm/module/apmhttp`?

**Comment by EDDYCJY** [comment]
@axw Yes, I changed it to go.elastic.co/apm/module/apmhttp.

The problematic version is 6.4.0 and the sample import path is `github.com/elastic/apm-agent-go/module/apmhttp` (Go APM Agents).

This example may need to be modified.

**Comment by axw** [comment]
I see, thanks for the info.

If you're using 6.4.0 you will need to use the `github.com/elastic/apm-agent-go/module/apmhttp` import path, but you will have to use the [0.5](https://github.com/elastic/apm-agent-go/tree/0.5) branch. I'll open an issue on Kibana to update the instructions.
