### ISSUE TITLE
Cannot convert frame to type uintptr

### ISSUE THREAD

**Issue by TimSatke** [elastic/apm-agent-go#408]
**Describe the bug**

On my CI server, i try to run a SAST with gosec, but I get a compile-time error, saying
```
# go.elastic.co/apm
../go.elastic.co/apm/error.go:361:19: cannot convert frame (type "github.com/pkg/errors".Frame) to type uintptr
```

**To Reproduce**
1. Run `docker run --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}" --volume "$PWD:/code" --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code` on my codebase
(The only location where I use APM is in [`server.go`](https://gitlab.com/iwritive/potassium/blob/develop/server.go#L37-39) as a gRPC unary interceptor)

As in [https://gitlab.com/iwritive/potassium/-/jobs/141919551](https://gitlab.com/iwritive/potassium/-/jobs/141919551)

**Expected behavior**

I don't get why there is a compile-time error, but to me it doesn't seem like a problem that can be solved by a re-compile (and it doesn't).

Maybe this is a problem with cross-platform compilation?

**Comment by axw** [comment]
@TimSatke it seems there was a breaking change to github.com/pkg/errors. I'll look into it immediately, but in the mean time you might want to vendor github.com/pkg/errors at 0.8.0, the last known working version.
