### ISSUE TITLE
ACTIVE=0 disables metrics

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-agent-go#412]
**Is your feature request related to a problem? Please describe.**
It's surprising that [ACTIVE](https://www.elastic.co/guide/en/apm/agent/go/current/configuration.html#config-active) only covers tracing and not metrics, especially for those upgrading an agent from a version that doesn't have metrics to one that does.

**Describe the solution you'd like**
Make `ACTIVE` cover all reporting from the agent and document common configurations users would like:

tracing on / metrics on: `ACTIVE=true`
tracing on / metrics off: `ACTIVE=true` `METRICS_INTERVAL=0s`
tracing off / metrics on: `ACTIVE=true` `TRANSACTION_SAMPLE_RATE=0`
tracing off / metrics off: `ACTIVE=false`

**Comment by axw** [comment]
> It's surprising that ACTIVE only covers tracing and not metrics, especially for those upgrading an agent from a version that doesn't have metrics to one that does.

I'm not sure I understand. Was this issue based on the out-of-date docs, or on observed behaviour? If you set `ACTIVE=false`, the background goroutine won't be started; no metrics will be gathered or sent.

**Comment by axw** [comment]
I've made a very minor change to the docs, but otherwise I don't think there's anything to do here; will close.

**Comment by graphaelli** [comment]
Thanks for the troubleshooting, I like this doc change.
