### ISSUE TITLE
List the Go APM in the APM official page

### ISSUE THREAD

**Issue by thalesfsp** [elastic/apm-agent-go#45]
![screen shot 2018-04-03 at 2 37 46 pm](https://user-images.githubusercontent.com/750360/38277251-9e94c9a4-374c-11e8-9543-ea1cebc1dd24.png)

Official page needs to be updated: https://www.elastic.co/solutions/apm

**Comment by axw** [comment]
Thank you for the reminder! I'll send a change to include it in the docs when the Go agent goes beta. I expect that won't be until the Elastic Stack 7.0 release.

**Comment by axw** [comment]
The docs are up at https://www.elastic.co/guide/en/apm/agent/go/current/index.html. I'll leave this open until the main page lists Go as well, which I'll add when the Go agent goes beta (should be soon).
