### ISSUE TITLE
Add ELASTIC_APM_INSTRUMENT config

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#451]
Add `ELASTIC_APM_INSTRUMENT` for disabling instrumentation modules such as `apmhttp`, `apmsql`, etc. This should not affect OpenTracing or other custom instrumentation.

See https://github.com/elastic/apm/issues/49

**Comment by basepi** [comment]
https://github.com/elastic/apm/issues/49 was closed, so this is no longer relevant.
