### ISSUE TITLE
Add method of specifying the service name for individual events

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#462]
In order to be able to report trace data on behalf of multiple services (e.g. in an Istio adapter), it will be necessary to override the service name on a per-event basis.

**Comment by alvarolobato** [comment]
Related: https://github.com/elastic/apm-server/issues/1175

**Comment by axw** [comment]
I'm going to close this one for now, will reopen if we continue on the path of an Istio adapter. I think we'd be better off with tracing in Envoy.
