### ISSUE TITLE
apmhttp: Calling the HTTP method within the RPC method, no link record is generated.

### ISSUE THREAD

**Issue by EDDYCJY** [elastic/apm-agent-go#468]
**Describe the bug**
I am calling the HTTP method inside the RPC method and no link record is generated in Kibana.

**To Reproduce**
1. Start a gRPC Server.
2. Write an HTTP method request web page or interface in an RPC method.
3. Request this RPC method.
4. Check if there is a span in Kibana.
5. There is no span information for HTTP requests.

**Code**

```
import (
	"context"
	"go.elastic.co/apm/module/apmhttp"
	"golang.org/x/net/context/ctxhttp"
	"net/http"
	"log"
        ...
)

...
var tracingClient = apmhttp.WrapClient(http.DefaultClient)

func (c *Server) GetInfo (ctx context.Context, ...) {
	...
	resp, err := ctxhttp.Get(ctx, tracingClient, "https://segmentfault.com/")
	if err != nil {
		log.Println(err)
	}
	log.Println(resp.Status)
}
```

**Expected behavior**
Calling an HTTP request in the RPC method, its span information should be displayed.

**Comment by axw** [comment]
Are you closing the response body? For outgoing HTTP requests, the span is only ended once the response body has been read or closed.

**Comment by EDDYCJY** [comment]
@axw .... is my test code missing Close, now solved.
But there is another problem. If you use defer `resp.Body.Close()`, then its span is not accurate.

**Comment by EDDYCJY** [comment]
In addition, what do you mean by reading, which behavior?

**Comment by axw** [comment]
@EDDYCJY 

> But there is another problem. If you use defer resp.Body.Close(), then its span is not accurate.

The reason the span is not ended immediately after `Get` returns is this: Get returns once it receives the response status code and headers from server. The server may continue writing the response body after Get returns. We consider that part of the same span.

You should generally close the response body as soon as possible anyway, as this can enable another HTTP request to reuse the connection.

> ps: If you use resp.Body.Close(), it will be dangerous when throwing an exception.

If you close the body immediately after checking the error, then there's no possibility of a panic. i.e. like this:

```go
resp, err := ctxhttp.Get(ctx, tracingClient, "https://segmentfault.com/")
if err != nil {
    log.Println(err)
}
resp.Body.Close()
```

> In addition, what do you mean by reading, which behavior?
>  
> ioutil.ReadAll(resp.Body)
> ...
> Do you mean this?

Yes, that would work. Or `io.Copy(ioutil.Discard, resp.Body)`. You could alternatively call `resp.Body.Close()` in addition to the deferred call. The deferred call will do nothing unless there is a panic.

**Comment by EDDYCJY** [comment]
@axw You are right, I have tried these methods. The span can be displayed normally in Kibana.

thank!

**Comment by axw** [comment]
Thanks for confirming. I'll update the docs to clarify this.
