### ISSUE TITLE
apmot logs stacktraces on inner spans 

### ISSUE THREAD

**Issue by dgcaron** [elastic/apm-agent-go#472]
We are using the APM opentracing module to trace the calls to our service and the initial requests work fine but subsequent calls are logged as an error:

example data:
```
{
  "_index": "apm-6.5.0-span-2019.03.12",
  "_type": "doc",
  "_id": "jubZcWkB3tb0rjh2wE5F",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-03-12T12:21:18.846Z",
    "processor": {
      "name": "transaction",
      "event": "span"
    },
    "span": {
      "hex_id": "9ad11c55e5db6233",
      "name": "HTTP client",
      "type": "external",
      "duration": {
        "us": 171502
      },
      "stacktrace": [
        {
          "exclude_from_grouping": false,
          "line": {
            "number": 275
          },
          "filename": "span.go",
          "abs_path": "/go/src/catalog/app/vendor/go.elastic.co/apm/span.go",
          "module": "catalog/app/vendor/go.elastic.co/apm",
          "function": "(*Span).End",
          "library_frame": true
        },
        {
          "line": {
            "number": 100
          },
          "filename": "span.go",
          "abs_path": "/go/src/catalog/app/vendor/go.elastic.co/apm/module/apmot/span.go",
          "module": "catalog/app/vendor/go.elastic.co/apm/module/apmot",
          "function": "(*otSpan).FinishWithOptions",
          "library_frame": true,
          "exclude_from_grouping": false
        },
        {
          "module": "catalog/app/vendor/go.elastic.co/apm/module/apmot",
          "function": "(*otSpan).Finish",
          "library_frame": true,
          "exclude_from_grouping": false,
          "line": {
            "number": 75
          },
          "filename": "span.go",
          "abs_path": "/go/src/catalog/app/vendor/go.elastic.co/apm/module/apmot/span.go"
        },
```

the first span inside the server gets logged correctly but all child spans have this stacktrace. 

**To Reproduce**
in our handler we do this:
```
spanCtx, _ := opentracing.GlobalTracer().Extract(opentracing.HTTPHeaders, opentracing.HTTPHeadersCarrier(r.Header))
span, ctx := opentracing.StartSpanFromContext(ctx, r.RequestURI, ext.RPCServerOption(spanCtx))
... do the work
span.Finish()
```

inside our methods we do this:
```
span, _ := opentracing.SartSpanFromContext(
  ctx, "inner method"
)
	
defer span.Finish()

.. do the work
```

**Expected behavior**
All inner spans show the same stacktrace cq. error where we would expect the ui to show something similar to the root of the trace.

**Comment by axw** [comment]
@dgcaron This is expected behaviour and not an error, though I can understand why it might not be obvious when looking at the data in that context.

We capture a stack trace for spans in order to show where in the source code the operation occurred, which can be helpful for remediation of bugs or performance issues. By default, stack traces are only captured for spans that exceed 5ms in duration.

See the "span details" at https://www.elastic.co/guide/en/kibana/6.6/spans.html for more, but please note that the Go agent does not currently capture source code. You will be able to see the source locations (function and file names, and line numbers), but not the source code like you can see in the screenshots of the Node.js agent.

**Comment by dgcaron** [comment]
Thanks for answering this!

**Comment by axw** [comment]
@dgcaron no worries. I'll close this now.

If you have any other questions or suggestions, please join us at https://discuss.elastic.co/c/apm. We'd love to hear your feedback on whether Elastic APM works well for you, and anything we could improve.
