### ISSUE TITLE
Add module for SQL Server driver support

### ISSUE THREAD

**Issue by vitiokss** [elastic/apm-agent-go#493]

**Comment by axw** [comment]
@vitiokss can you please expand a little on what you're looking for?

Are you asking for a new module like https://github.com/elastic/apm-agent-go/tree/master/module/apmsql/mysql, but for denisenkom/go-mssqldb?

Have you tried `apmsql` with this driver?

**Comment by vitiokss** [comment]
@axw exactly what I meant, the dialect to support `denisenkom/go-mssqldb`. The documentation of APM agent says it supports just a set of databases dialects (postgres, mysql, sqlite3) https://www.elastic.co/guide/en/apm/agent/go/current/supported-tech.html#supported-tech-databases

I have tried to setup it following 2 cases, and none of them worked.
  1. Used just apmsql.Open("sqlserver|mssql"), it gives me an error of 
```panic: sql: unknown driver "apm/sqlserver" (forgotten import?)```

  2. Tried to register the driver in init (apmsql.Register(...)) and then connect to it. That eliminates the error and boots the service. However nothing is being logged in the APM client in (SpanContext).

Please let me know if I should try different approach of doing it.

**Comment by axw** [comment]
> Tried to register the driver in init (apmsql.Register(...)) and then connect to it. That eliminates the error and boots the service. However nothing is being logged in the APM client in (SpanContext).

This is the right approach. Are you using the database/sql context methods, and passing in a request context?

This works for me:

```go
package main

import (
        "context"
        "log"

        mssql "github.com/denisenkom/go-mssqldb"
        "github.com/kr/pretty"

        "go.elastic.co/apm/apmtest"
        "go.elastic.co/apm/module/apmsql"
)

func main() {
        apmsql.Register("sqlserver", &mssql.Driver{})
        db, err := apmsql.Open("sqlserver", "sqlserver://username:password@host/instance")
        if err != nil {
                log.Fatal(err)
        }
        defer db.Close()

        _, spans, _ := apmtest.WithTransaction(func(ctx context.Context) {
                db.QueryRowContext(ctx, "SELECT * FROM FOO")
        })
        pretty.Println(spans)
}
```

Note that you must use QueryRowContext vs. QueryRow for a span to be reported, and the context you pass in must have an apm.Transaction in it. If you're making the database query from an HTTP handler, your mux/router needs to be instrumented, and you must pass the request context into the database query.

**Comment by vitiokss** [comment]
@axw great it seems to work. Thank you!
I was missing to attach the context to the query, that causes the problem.

Closing the issue :)

**Comment by axw** [comment]
@vitiokss great! :)

I will open a new issue to add an mssql dialect package under apmsql to simplify the registration, and to parse the DSN. What's will be functional, but will miss a couple of minor things from the span context like the database instance name.
