### ISSUE TITLE
Feature: add apmsql/mssqldb

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#496]
See https://github.com/elastic/apm-agent-go/issues/493. We should add another package for registering an instrumented MS SQL driver using https://github.com/denisenkom/go-mssqldb, and providing a DSN parser.

**Comment by theodesp** [comment]
I can give it a try when we finish with the `apmbuffalo` unless someone does this first.

**Comment by thibleroy** [comment]
Hello, this issue can be closed? https://github.com/elastic/apm-agent-go/pull/1356
Can we use the module with the microsoft's mssql driver?

**Comment by dmathieu** [comment]
Thank you for the bump here. Yes, I believe this issue can be closed, I'll do so.
As for the Microsoft mssql driver, not it cannot be used right now, as we still use the old `denisenkom/go-mssqldb` version.

I have opened https://github.com/elastic/apm-agent-go/pull/1569 to make the switch.
