### ISSUE TITLE
Custom dashboard to visualize the runtime metrics

### ISSUE THREAD

**Issue by nehaduggal** [elastic/apm-agent-go#504]
Custom dashboard in the apm=contrib repo to visualize the runtime metrics collected by default by the Go agent.

**Comment by axw** [comment]
I had https://github.com/elastic/apm-agent-go/issues/490 open for this. It has 0 characters in the description, so I'll keep this one ;)

**Comment by axw** [comment]
As mentioned in https://github.com/elastic/apm-agent-go/issues/161, we're currently missing the "GCSys" value from our reported metrics. We should add that.
