### ISSUE TITLE
Generate explain for slow database queries

### ISSUE THREAD

**Issue by macnibblet** [elastic/apm-agent-go#520]
**Is your feature request related to a problem? Please describe.**
A feature I really like from Newrelic that I would love to see is transaction tracking of slow queries that exceed a certain threshold. 

**Describe the solution you'd like**
If the duration for a query exceeds a configurable interval, then the hook integrations should generate a explain query and store it with the span. 

This would also require integration with the APM server / UI.

**Comment by axw** [comment]
Sounds like a great idea to me. I'm transferring this to the elastic/apm repo, since it's relevant to all agents as well as the server and UI.
