### ISSUE TITLE
apmgrpc: Add support for ignoring urls

### ISSUE THREAD

**Issue by omrishtam** [elastic/apm-agent-go#530]
I've been working on putting `apmgrpc`'s `UnaryServerInterceptor` in my gRPC server which has a health check method, and needed to make the apm agent to not start a transaction for that health check method and ignore incoming requests to that method, as it's possible with HTTP servers that use the agent.

I tried using `ELASTIC_APM_IGNORE_URLS` or with `WithServerRequestIgnorer` as possible with `apmhttp`, but setting a `RequestIgnorerFunc` option is only possible on http modules of apm so there's no way to ignore a method request on gRPC server which has an interceptor from apmgrpc.

I looked into the documentation of the agent and saw that `apmhttp` implements this functionality for HTTP servers.
I think that `apmgrpc` should match `apmhttp` and also respect the `ELASTIC_APM_IGNORE_URLS` environment variable and export the `WithServerRequestIgnorer` and other functions that are used to set up the `requestIgnorer` of the `UnaryInterceptor`.

This means that `serverOption` struct should add `requestIgnorer` field, and the `NewUnaryServerInterceptor` function should return an `grpc.UnaryServerInterceptor` that implements the check whether to ignore the request or not.
The functionality seems to be easy to implement since there are few changes needed from `apmhttp` implementation for this to work for gRPC.

This is the only way I considered that would solve this issue I have with the agent and it's pretty important since gRPC servers are becoming more widely used.

**Comment by axw** [comment]
@omrishtam thanks for opening the issue. Adding a RequestIgnorer type and option sounds good to me. I'm not too keen on reusing the environment variable `ELASTIC_APM_IGNORE_URLS`, since it's not really a URL but an RPC method name.

Do you need the environment variable at the moment?

**Comment by omrishtam** [comment]
Thanks for responding, I've [forked](https://github.com/omrishtam/apm-agent-go) the repo to make a draft of the change that would work for me, it should be easy to just change the name of the environment variable [here](https://github.com/omrishtam/apm-agent-go/blob/596f767ce13dca8a522ebfafbe0c35254c67f0e8/module/apmgrpc/ignorer.go#L29), just need to decide on its name.

What I did was basically copying the relevant functions and types from `apmhttp` to `apmgrpc`, and implemented the tests to check it works for `apmgrpc`.
I could make a PR if you would like me to.

**Comment by axw** [comment]
@omrishtam thanks, the code looks good. One thing I'm wondering is if it would make sense to make the RequestIgnorerFunc receive a `*grpc.UnaryServerInfo`, rather than just pulling out the method name. That might be more future-proof.

Regarding the environment variable name - my question was more like this: do you need to use an environment variable at all?

If you can hard-code your app to pass a RequestIgnorer into apmgrpc for now, then I think we could merge your changes with some minor changes. Otherwise, it might take a while before we settle on an environment variable name that all of the agent devs agree on.

**Comment by omrishtam** [comment]
@axw I could make RequestIgnorerFunc receive a `*grpc.UnaryServerInfo`, I wasn't so sure about that myself, but I agree that this would probably be a better approach.

Regarding the environment variable, I thought that if there is one for HTTP routes then there should be one for gRPC too, but of course this isn't as necessary as the ability to pass a RequestIgnorer which is my main issue.

I agree that I should just make RequestIgnorerFunc receive a `*grpc.UnaryServerInfo`, remove the environment variable usage, and then you could merge my changes with tweaks as requested later for the PR.

And maybe keep the idea of another environment variable to another time, if the discussion/need ever comes up again, since discussing it now would just delay the addition of the RequestIgnorer.

I'll make a PR after making the changes on my fork if you approve this 😀

**Comment by axw** [comment]
@omrishtam that all sounds great to me, thank you. Agreed that an environment variable makes sense - I'll create an issue to track it later. I'm travelling this week, so I may not get to your PR immediately.

**Comment by axw** [comment]
Closed by #531
