### ISSUE TITLE
Support OpenTracing Baggage

### ISSUE THREAD

**Issue by dozer47528** [elastic/apm-agent-go#537]
Any plan for that?

**Comment by axw** [comment]
@dozer47528 no plans for baggage at the moment.

If you have a use-case in mind for baggage, please open a new topic on the Discuss forum: https://discuss.elastic.co/c/apm. Thanks!

**Comment by dozer47528** [comment]
Same here:
https://www.premiumoutlets.com/outlet/woodbury-common/stores
