### ISSUE TITLE
request body is missing sometimes on APM

### ISSUE THREAD

**Issue by ikropotov** [elastic/apm-agent-go#568]
I have wrapped with apmhttp one of our go services, to track requests on kibana. And for some requests body was missing within apm logs. 

I've dived deeper into your plugin and explored what was going on there, and it turned out that on this line https://github.com/elastic/apm-agent-go/blob/master/capturebody.go#L115 the error appeared, complaining that bc.originalBody is already closed, and cannot be read.

Going further down the hole, I've discovered that we actually use that tool as a little proxy, so when request passed down to our tool here https://github.com/elastic/apm-agent-go/blob/master/module/apmhttp/handler.go#L87 we are doing a further request to other endpoints, and when they reply we write answer to `w http.ResponseWriter` to handle it back.

Looking at `w http.ResponseWriter` definition at http lib https://github.com/golang/go/blob/master/src/net/http/server.go#L127, I came across the comment `handlers should read any needed request body data before writing the response`, so it came out that writing to ResponseWriter sometimes marks body as being read, and afterwards apm plugin is trying to read it again...

So I suppose a proper behaviour would be to read original request body beforehand, and attach the copy to be sent to APM - exactly that I've done in my fork, and will submit a PR.

May be you can merge it or suggest some other solution/improvement.

Thanks, Ivan

**Comment by axw** [comment]
@ikropotov thanks for opening the issue and PR!

`Tracer.CaptureHTTPRequestBody` wraps the body so that whatever the underlying handler reads is buffered. So we're relying on the handler to read the body. Is your application code not doing that?

**Comment by ikropotov** [comment]
@axw our handler is reading it and it's not the question about the Teed part, the issue is that here
https://github.com/elastic/apm-agent-go/blob/master/capturebody.go#L114 
it tries to read `bc.originalBody` in addition to teed body, which is already closed by writing to `w http.ResponseWriter`, and returns an error here https://github.com/elastic/apm-agent-go/blob/master/capturebody.go#L117
however if you remove it reading from originalBody, it will be missing in apm request, in case teed part is not being read in handler (that's why I am reading it fully first in the PR)

**Comment by axw** [comment]
@ikropotov ahh I see, because that error we bail out and don't set anything. Got it.

I'll have to think on what the ideal solution is. As mentioned on the PR, I don't think that reading it all up front is the right way, because of the possibility of a streaming body.

**Comment by axw** [comment]
@ikropotov I think the safest thing to do would be to ignore the error returned by `ioutil.ReadAll`, and just use the result. Even if there's an error, whatever data is read will be returned. We would only guarantee that whatever is read by the handler will be recorded. What do you think?

Given that we truncate the recorded body to 1024 bytes, I'd say it's generally pretty likely that the request body will be buffered, so reading from the closed body shouldn't be a problem. We really should be wrapping the MultiReader in a LimitedReader to limit reading to 1024 bytes.

**Comment by ikropotov** [comment]
@axw I haven't tried this option, I suppose it could work as long as data is properly read 
_I was thinking that if `ioutil.ReadAll` ends up with err, then data read either truncated or corrupted, and not sure about ordering there, 
i.e `io.MultiReader(bytes.NewReader(bc.buffer.Bytes()), bc.originalBody)` - are we sure that it reads bc.buffer first, and then errors on originalBody, rather than other way around leaving result empty ?_

**Comment by ikropotov** [comment]
I've tweaked my test for reading body and played around your suggestion:
https://github.com/elastic/apm-agent-go/pull/569/commits/db99fd22e0ee33b048b941d1a2fd1d18d75450a9
And it looks good if we just ignore that error

**Comment by axw** [comment]
@ikropotov the docs for ioutil.ReadAll say this:

> ReadAll reads from r until an error or EOF and returns the data it read.

I think the only change we need is this:

```diff
diff --git a/capturebody.go b/capturebody.go
index bcba2201..33998151 100644
--- a/capturebody.go
+++ b/capturebody.go
@@ -110,13 +110,10 @@ func (bc *BodyCapturer) setContext(out *model.RequestBody) bool {
                return true
        }
 
-       // Read from the buffer and anything remaining in the body.
+       // Read from the buffer and anything remaining in the body, ignoring
+       // any errors (e.g. http.ErrBodyReadAfterClose) while reading.
        r := io.MultiReader(bytes.NewReader(bc.buffer.Bytes()), bc.originalBody)
-       all, err := ioutil.ReadAll(r)
-       if err != nil {
-               // TODO(axw) log error?
-               return false
-       }
+       all, _ := ioutil.ReadAll(r)
        out.Raw = truncateString(string(all))
        return true
 }                                                                        
```

To test this, I'd prefer we change `testPostTransaction` to start an httptest.Server, and change the "capture body that has been closed" test's handler to do the following:

```go
 ioutil.ReadAll(req.Body)
req.Body.Close()
```

Then you can get rid of the "closingBody" type, as there's no longer a need to mock the request body.

**Comment by ikropotov** [comment]
As I recall the `req.Body` for `http.HandlerFunc` is straightforward ReadCloser and was not preventing/erroring read on closed body as `http.body` does, that's why I mimicked it to be more similar to real life scenario that I faced and cover it with the test

**Comment by axw** [comment]
@ikropotov I've put up an alternative PR: https://github.com/elastic/apm-agent-go/pull/575

I'd appreciate if you could have a look and test if it solves the issue for you.

> As I recall the req.Body for http.HandlerFunc package is straightforward ReadCloser and was not preventing/erroring read on closed body as http.body does, that's why I mimicked it to be more similar to real life scenario that I faced and cover it with the test. It looks for me like more robust coverage.

When using httptest.Server (a real net/http server), the request handler will be given a req.Body that has the `http.body` type. Reading and closing the body will cause the error you observed. I added a test to my PR to illustrate (it causes the test to fail without the other changes to capture_body.go).

**Comment by ikropotov** [comment]
@axw I've tested it and it's been working

**Comment by axw** [comment]
Great, thank you for testing. I'll close your PR and merge #575.
Thank you for the change all the same!
