### ISSUE TITLE
Custom contextual information API

### ISSUE THREAD

**Issue by matiasanaya** [elastic/apm-agent-go#579]
**Additional context**
[The doc](https://www.elastic.co/guide/en/apm/get-started/current/metadata.html#custom-fields) suggests that custom context values are coming soon. Any timeframe available?

We need this feature.

**Comment by axw** [comment]
@matiasanaya thanks for opening the issue, this slipped off my radar. This should be pretty straightforward, I'm looking into it now.

**Comment by axw** [comment]
@matiasanaya I've just merged support into master. If you could have a look and make sure it works for you that would be great.

**Comment by matiasanaya** [comment]
wow, that was quick 💪. I'll have a look in 12hs, thanks in advance!

**Comment by matiasanaya** [comment]
Works great for me. Thanks again 🥇

**Comment by axw** [comment]
Great, thanks for confirming!
