### ISSUE TITLE
Truncate large captured body

### ISSUE THREAD

**Issue by omerzamir** [elastic/apm-agent-go#580]
**Describe the bug**
When capturing a request body, memory usage is multiplied. This causes the memory usage to explode as the request's body gets bigger.

**To Reproduce**
1. Use this config: ELASTIC_APM_CAPTURE_BODY anything but 'off'.
2. Send a request to the server with a large request body, for example a file upload.
3. See the memory usage rise much higher than having the config set to 'off', and it might crash the server.

**Expected behavior**
The APM agent for nodejs implemented a limit of 2 KiB for the request body, after which the recorded body would be truncated to the 2 KiB limit, as documented in [apm agent node config docs](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#capture-body).
I expect apm agent for go to handle this issue similarly and truncate the recorded body to a reasonable limit for which the memory usage wouldn't hurt the performance of the server running the agent.

**Comment by axw** [comment]
@omerzamir thanks for opening this!

I made some improvements in this area last week (https://github.com/elastic/apm-agent-go/pull/575), but there's more to be done for sure.

We truncate the body at 1024 Unicode characters (up to 4KiB). The missing piece at the moment is to limit how much we buffer from via the TeeReader in capture_body.go, prior to truncation.

**Comment by omerzamir** [comment]
@axw  BTW, forgot to mention that I encountered this issue on my gin-gonic server.

**Comment by axw** [comment]
@omerzamir I've just merged some improvements to request body capture. Can you please try it out and let me know if you still have any issues?
