### ISSUE TITLE
undefined: sqlutil.QuerySignature in go.elastic.co/apm/module/apmsql@v1.3.0/driver.go:145:9

### ISSUE THREAD

**Issue by anvari1313** [elastic/apm-agent-go#584]
**Describe the bug**
I'm writing a go application with the Echo framework and I use MariaDB and Redis. I use [apmgoredis](https://github.com/elastic/apm-agent-go/tree/master/module/apmgoredis) and [apmsql](https://github.com/elastic/apm-agent-go/tree/master/module/apmsql) for adding metrics on transactions with Redis and MariaDB. When I add APM echo logger middleware to the project, I get the following error in my `go vet` command:

`# go.elastic.co/apm/module/apmsql
../../../../pkg/mod/go.elastic.co/apm/module/apmsql@v1.3.0/driver.go:145:9: undefined: sqlutil.QuerySignature
`

By the way, I'm using golang 1.12, with echo v4

**Comment by axw** [comment]
Can you please share your `go.mod` file?

**Comment by anvari1313** [comment]
This is my go mod file:
`
module github.com/anvari1313/some-repo

go 1.12

require (
	github.com/BurntSushi/toml v0.3.1 // indirect
	github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
	github.com/elastic/go-sysinfo v1.0.1 // indirect
	github.com/elliotchance/phpserialize v1.1.0
	github.com/go-playground/locales v0.12.1 // indirect
	github.com/go-playground/universal-translator v0.16.0 // indirect
	github.com/go-redis/redis v6.15.3-0.20190424063336-97e6ed817821+incompatible
	github.com/go-sql-driver/mysql v1.4.1
	github.com/golang/protobuf v1.3.1 // indirect
	github.com/google/go-cmp v0.3.0 // indirect
	github.com/hashicorp/hcl v0.0.0-20180404174102-ef8a98b0bbce // indirect
	github.com/labstack/echo/v4 v4.1.5
	github.com/labstack/gommon v0.2.8
	github.com/leodido/go-urn v1.1.0 // indirect
	github.com/magiconair/properties v1.8.0 // indirect
	github.com/mitchellh/mapstructure v0.0.0-20180715050151-f15292f7a699 // indirect
	github.com/mmcloughlin/geohash v0.0.0-20180909114810-59020f29e94a
	github.com/newrelic/go-agent v2.0.0+incompatible
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/pelletier/go-toml v1.2.0 // indirect
	github.com/prometheus/procfs v0.0.0-20190507164030-5867b95ac084 // indirect
	github.com/santhosh-tekuri/jsonschema v1.2.4 // indirect
	github.com/spf13/afero v1.1.1 // indirect
	github.com/spf13/cast v1.2.0 // indirect
	github.com/spf13/jwalterweatherman v0.0.0-20180109140146-7c0cea34c8ec // indirect
	github.com/spf13/pflag v1.0.1 // indirect
	github.com/spf13/viper v1.0.2
	github.com/stretchr/objx v0.2.0 // indirect
	github.com/stretchr/testify v1.3.0
	go.elastic.co/apm/module/apmechov4 v1.4.0
	go.elastic.co/apm/module/apmgoredis v0.0.0-20190503080157-47cc289609d7
	go.elastic.co/apm/module/apmsql v1.3.0
	golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f // indirect
	golang.org/x/net v0.0.0-20190514140710-3ec191127204 // indirect
	golang.org/x/sys v0.0.0-20190514135907-3a4b5fb9f71f // indirect
	golang.org/x/text v0.3.2 // indirect
	gopkg.in/go-playground/assert.v1 v1.2.1 // indirect
	gopkg.in/go-playground/validator.v9 v9.28.0
	gopkg.in/natefinch/lumberjack.v2 v2.0.0
	gopkg.in/yaml.v2 v2.2.2 // indirect
)
`

**Comment by anvari1313** [comment]
I think that I solve the issue by adding 
`go.elastic.co/apm` 
to my 
`go.mod` file.
 And for solving the `go mod tidy` problem (it removes `go.elastic.co/apm` because there is no need to explicitly import it), I added 
`import (
     _ "go.elastic.co/apm"
)
`
to my import list, somewhere in the application.

**Comment by axw** [comment]
@anvari1313 thanks for the update.

The way I would have recommended that you fix this is by setting each of the `module/apm...` dependencies to the same version. `module/apmsql` has a dependency on an internal package of the apm repo, which requires that they all have the same version.
