### ISSUE TITLE
Gin with Gorm

### ISSUE THREAD

**Issue by lily-lee** [elastic/apm-agent-go#585]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions. 

Hi, I need help.

I use apmgin and apmgorm.

```go

db, err = apmgorm.Open("mysql", dsn)

r.Use(apmgin.Middleware(r))

func GetOrderTrade(ctx *gin.Context) {
    db = apmgorm.WithContext(ctx, db)
    trades := []models.OrderTrade{}
    db.Find(&trades)
    ctx.JSON(200, trades)
}
```

There is no gorm trace information under http routes information.

**Comment by axw** [comment]
You need to use the `net/http.Request.Context()` method. Try this:

```go
db := apmgorm.WithContext(ctx.Request.Context(), db)
```

**Comment by lily-lee** [comment]
Thank you ! It works.

**Comment by axw** [comment]
Great, thanks for confirming. Closing this now, since it's working.
There's an issue open (now linked to this) to improve the docs.

**Comment by lily-lee** [comment]
@axw Hi, I met the same question when I use gin and go-redis.

```go
client := apmgoredis.Wrap(redis.NewClient(&redis.Options{
	Addr: "127.0.0.1:6379",
})).WithContext(ctx.Request.Context())
fmt.Println("redis val: ", client.Get("lily").String())
```

**Comment by axw** [comment]
@lily-lee does that work, using `ctx.Request.Context()` in your Redis example?

Are you still having issues, or are you just letting me know you had to solve it there too? (You'll need to pass `ctx.Request.Context()` into any APM module that requires context.)

**Comment by lily-lee** [comment]
@axw Thank u.  It's working. I use `ctx.Request.Context()` every where. I misunderstood the `GET` timeline. I thought that it's http.GET. I checkout the detail page and it's type is DB.  In fact, it is the redis timeline. The Go program's timeline page is not like Ruby's.

Ruby's APM timeline page is better, there are different icons to show user the type and there are also time durations.

🙏thank you so much.

**Comment by axw** [comment]
@lily-lee OK great. If you have time, could you please provide a screenshot of the Ruby and Go timelines so I can compare? Assuming you're using the same APM Server/Kibana for both, they should look similar.

**Comment by lily-lee** [comment]
@axw Oh, that reminds me.

They are not the save server.  

Go use apm-server-6.5.4-darwin-x86_64/kibana 6.5.4.

Ruby use 6.6.2/6.6.2

Thank you so much, you help me a lot !

**Comment by axw** [comment]
Ah :) That would probably explain the visual differences. Thanks for the feedback!
