### ISSUE TITLE
Review which tags we should build

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-go#608]
right now, we build every tag is in the repository, but maybe it is not needed there are a bunch of tags like `module/*` that probably can be skipped.

**Comment by axw** [comment]
Yeah we definitely don't need to run tests for all of the `module/*` tags; they exist only to support Go module lookup. We should test: master and vN.N.N excluding v0.N.N.

**Comment by v1v** [comment]
Changes have been already applied, for the record

![image](https://user-images.githubusercontent.com/2871786/68765716-58ac7b00-0615-11ea-94fc-9742af1aee9b.png)


![image](https://user-images.githubusercontent.com/2871786/68765765-77ab0d00-0615-11ea-9aee-025ed968e25c.png)
