### ISSUE TITLE
module/apmzerolog: allow user to override level checks in Writer

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#636]
**Is your feature request related to a problem? Please describe.**

The apmzerolog.Writer type can be used to send error-level logs to Elastic APM as error events. The level checking is hard-coded, so that Error, Fatal, and Panic logs are all sent:

https://github.com/elastic/apm-agent-go/blob/41d6c9b1f1d8b6e49742b44364d1da94fae58ea3/module/apmzerolog/writer.go#L91-L93

Users may want to send only Fatal and Panic, or just Panic logs. They could do this by wrapping the Writer with another custom zerolog.LevelWriter, but that's not very friendly. We should permit users to specify the minimum level of log records to send to send as errors to APM Server.

**Describe the solution you'd like**

Add a new field to Writer to control the minimum level of logs to send as errors to the APM Server. We should continue to send only zerolog.ErrorLevel or greater, but users may increase the minimum level to something greater so that only Fatal/Panic logs are sent.

```go
type Writer {
    // MinLevel holds the minimum level of logs to send to Elastic APM as errors.
    //
    // MinLevel must be greater than or equal to zerolog.ErrorLevel. If it is less than
    // this, it will be ignored and zerolog.Error will be used as the minimum instead.
    MinLevel zerolog.Level

    ...
}
```

**Describe alternatives you've considered**

I initially thought we could check if Writer.MinLevel were set, and then use that as the minimum (with no additional check that the level is >= zerolog.ErrorLevel). This won't work well, because the zero value of zerolog.Level is zerolog.DebugLevel, so a zero-value apmzerolog.Writer will send all logs as errors which is definitely not what we want. Non-error logs shouldn't be sent to APM anyway.

**Additional context**

https://discuss.elastic.co/t/can-apmzerolog-send-every-log-to-link-tracking/199802

**Comment by EDDYCJY** [comment]
👍
