### ISSUE TITLE
go test ./... fails

### ISSUE THREAD

**Issue by jonbodner** [elastic/apm-agent-go#667]
**Describe the bug**
Running `go test ./...` produces an error.

**To Reproduce**
1. `git clone https://github.com/elastic/apm-agent-go.git`
2. `cd apm-agent-go`
3. `go test ./...`
4. See:

```
2019/10/30 11:59:22 cannot find package "go.elastic.co/apm/internal/apmschema" in any of:
	/usr/local/go/src/go.elastic.co/apm/internal/apmschema (from $GOROOT)
	/home/jon/go/src/go.elastic.co/apm/internal/apmschema (from $GOPATH)
FAIL	go.elastic.co/apm	0.008s
```
(rest of tests pass)

**Expected behavior**
Tests should pass

I have traced this issue down to the line:

```
	pkg, err := build.Default.Import("go.elastic.co/apm/internal/apmschema", "", build.FindOnly)
```
 in `internal/apmschema/schema.go`.

I expected this to work because the Contributing.md document says:

**The tests currently do not require any external resources, so just run go test ./....**

I am using the following Go version:
`go version go1.13.3 linux/amd64`

**Comment by jonbodner** [comment]
The problem is that the technique used in internal/apmschema/schema.go to find the jsonschema files doesn't work outside of the GOPATH. Here is code that will work both inside and outside of the GOPATH. Replace the start of the `init()` function with this:

```
	_, filename, _, _ := runtime.Caller(0)
	dir := strings.TrimRight(filename,"schema.go")
	compiler := jsonschema.NewCompiler()
	compiler.Draft = jsonschema.Draft4
	schemaDir := path.Join(filepath.ToSlash(dir), "jsonschema")
```

**Comment by axw** [comment]
Thanks @jonbodner! The agent was started before modules were a thing, so still have a couple of assumptions like this. I'll get this fixed shortly - thanks for the snippet, that's much smarter.
