### ISSUE TITLE
Document ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER config

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#685]
See https://github.com/elastic/apm-agent-go/pull/675#issuecomment-560091774 - we need to document ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER.

**Comment by beniwohli** [comment]
FWIW, I documented it like this: https://github.com/elastic/apm-agent-python/pull/660/commits/d9dc4df9e8d8

**Comment by axw** [comment]
Thanks @beniwohli! I'll pinch that once I've added support for tracestate.
