### ISSUE TITLE
Lambda integration

### ISSUE THREAD

**Issue by dcu** [elastic/apm-agent-go#749]
**Is your feature request related to a problem? Please describe.**
Add an easy way to integrate with AWS Lambda

**Describe the solution you'd like**
Probably functions to wrap the lambda requests and maybe other AWS services

**Comment by axw** [comment]
There's a module for that: [go.elastic.co/apm/module/apmlambda](https://github.com/elastic/apm-agent-go/tree/master/module/apmlambda). It's considered experimental, and may change in a non-backwards compatible way. It's pretty basic at the moment, and not the ideal implementation, but try it out and let us know what works, what doesn't, and what is missing for you.

All you should need to do is add this to your code:

```go
import _ "go.elastic.co/apm/module/apmlambda"
```

**Comment by dcu** [comment]
and how's the ES server (where the data should go) configured?

**Comment by axw** [comment]
The Go agent is configured through environment variables. It communicates with the APM Server over HTTP, and its URL is specified via [ELASTIC_APM_SERVER_URL](https://www.elastic.co/guide/en/apm/agent/go/current/configuration.html#config-server-url).

As we already have Lambda integration, I'm going to close this issue. If there's something missing, or you have further questions, please open a topic at https://discuss.elastic.co/c/apm.
