### ISSUE TITLE
How can I custom transaction trace status?

### ISSUE THREAD

**Issue by Chanasit** [elastic/apm-agent-go#766]
Hi Guys,
I working on Kafka consumer that didn't provide HTTP response status 
so I create custom Transaction trace like this
<br>
![image](https://user-images.githubusercontent.com/18435912/81397962-8997e380-9152-11ea-8045-004aa33baa55.png)
<br>
How I can change N/A tag to something else?
As Image Below here
![image](https://user-images.githubusercontent.com/18435912/81397659-f8287180-9151-11ea-8e67-eb998f0d294f.png)

**Comment by axw** [comment]
The "HTTP 2xx" value for HTTP requests comes from the transaction result:

https://github.com/elastic/apm-agent-go/blob/f07b51f3e6132a148b258a72781e6616409fd477/module/apmhttp/handler.go#L133

You can set `tx.Result = "..."` any time before calling `tx.End()`, like:

```go
tx := apm.DefaultTracer.StartTransaction("message-out-topic-consumer", "request")
defer tx.End()
// do some work...
tx.Result = "success"
```

If you have any more questions, please create a topic at https://discuss.elastic.co/c/apm. We prefer to use GitHub issues for bugs and feature requests. Thank you.

**Comment by Chanasit** [comment]
Thank you very much, it's work @axw
