### ISSUE TITLE
RFC: make DefaultTracer a function, defer init to first call

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#775]
This would be an alternative to https://github.com/elastic/apm-agent-go/issues/773. Rather than initialising the default tracer at package init time, make DefaultTracer a function and initialise the tracer on first call. We would probably also need to supply a SetDefaultTracer companion function.

**Comment by billyplus** [comment]
> Tracers are independent by design, so creating a tracer should not interfere with another one. 
As I expect, I can have multiple tracers in my app, which means default tracer may or may not bind with enviroment var, but other tracers are not. So NewTracer function should take config as argument to init a new tracer, then I can SetDefaultTracer to replace default tracer to the new one.
That not breaks things.

**Comment by billyplus** [comment]
What we go now is, when we create tracer with NewTracer, the ServerURL is parsed from enviroment var, which is always the same, then we got duplicate tracer with the same ServerURL.

**Comment by axw** [comment]
@billyplus I just want to make sure I understand: does the approach I described above satisfy your requirements? i.e. in your app you could do something like:

```go
transport1, err := transport.NewHTTPTransport()
tracer1, err := apm.NewTracerOptions(apm.TracerOptions{
    Transport: transport1,
    ServiceName: "service1",
    ServiceVersion: "version1",
})

transport2, err := transport.NewHTTPTransport()
transport2.SetServerURL(...) // override ELASTIC_APM_SERVER_URLS for tracer2
tracer2, err := apm.NewTracerOptions(apm.TracerOptions{
    Transport: transport2,
    ServiceName: "service2",
    ServiceVersion: "version2",
}

apm.SetDefaultTracer(tracer1)
apm.DefaultTracer() // returns tracer1, which uses ELASTIC_APM_SERVER_URLS
```

**Comment by billyplus** [comment]
@axw Yeah. Something like that. Environment variables could be default setting. And the tracers created manually should have the ability to override the default settings.
