### ISSUE TITLE
Unimplemented ReadFrom() in wrapped http response writer

### ISSUE THREAD

**Issue by titpetric** [elastic/apm-agent-go#826]
**Describe the bug**

The net/http standard library has some public functions which aren't exposed with the ResponseWriter interface, namely:

```
// ReadFrom is here to optimize copying from an *os.File regular file
// to a *net.TCPConn with sendfile.
func (w *response) ReadFrom(src io.Reader) (n int64, err error) {
```

As such, the default ResponseWriter can also satisfy the io.ReaderFrom interface. Unfortunately, [go-chi/chi](https://github.com/go-chi/chi/blob/12ebe3332f86ee21554ecfbef430bdf376be7f5f/middleware/wrap_writer.go#L27) is relying on that implementation. In practice this means that I can't instrument a websocket connection with apmhttp.

**Expected behavior**

The ReadFrom() function is implemented for the wrapped writer interfaces so a wrapped writer can satisfy io.ReaderFrom

**Comment by axw** [comment]
Thanks for reporting the issue. I'll take a look into it.
