### ISSUE TITLE
tx.Discard() should set tx.TransactionData to nil as tx.End()

### ISSUE THREAD

**Issue by mcfog** [elastic/apm-agent-go#835]
**Describe the bug**
Before [this change](https://github.com/elastic/apm-agent-go/pull/478/commits/d4ce90ae56156a6bcb527e3b97816c0ea9adc1b0#diff-63ab601287b8b9c040760fe0bdd288f55b73f37cd7e4f1e519bea2bd43a18bbaL211),  `tx.Discard()` used to clear `tx.TransactionData` just as `tx.End()`. This makes it safe to call `Discard()` multiple times and/or mix with `End()` calls. But now calling `End()` after `Discard()` leads to panic (under some workload), and since internal `tx.ended` would report false after `Discard()`, this may also lead to other unexpected behaviors.

**To Reproduce**

```go
package main

import (
	"fmt"
	"sync"

	"go.elastic.co/apm/transport/transporttest"
)

func main() {
	fmt.Println("Hello, playground")

	tracer, _ := transporttest.NewRecorderTracer()
	defer tracer.Close()

	wg := new(sync.WaitGroup)
	for i := 0; i < 100000; i++ { // increase this if your machine is fast
		wg.Add(1)
		go func() {
			tx := tracer.StartTransaction("name", "type")
			tx.Discard()
			tx.End()
			wg.Done()
		}()
	}
	wg.Wait()
}
```

**Expected behavior**

Call `Discard` should clear `tx.TransactionData`

**Comment by axw** [comment]
Ouch! Sorry, and thanks very much for reporting this.
