### ISSUE TITLE
Let applications enable support for follows-from spans

### ISSUE THREAD

**Issue by randomswdev** [elastic/apm-agent-go#843]
In the opentracing moduke, the file [context.go](https://github.com/elastic/apm-agent-go/blob/v1.9.0/module/apmot/context.go), contains logig to consider valid only the spans generated by a child-of ref.
A comment in the file explains that a unit test is able to override this behaviour.

Is there any plan to overcome this limitation, that creates troubles when using the tracing module with third party libraries?

Or at least do you think it would be possible to let applications do th same overriding the unit testing does?

In this latter case it is up to the application developer to evaluate if it is safe to override the logic that checks which spans are "valid".

**Comment by axw** [comment]
Hi @randomswdev, thanks for opening the issue!

Right now we don't have any concrete plans to accept follows-from references. We started discussing it a while back (https://github.com/elastic/apm/issues/122), but that has stalled.

I would be open to adding a tracer option that overrides the default behaviour, but as you say it would be up to the developer to make sure that it's safe to do so, and any semantic issues that arise are acceptable to them. Are you interested in submitting a PR that adds an option?

**Comment by axw** [comment]
Closed by #847
