### ISSUE TITLE
Define a SQL driver unwrapping method

### ISSUE THREAD

**Issue by Julio-Guerra** [elastic/apm-agent-go#848]
Hey Elastic :-)

**Is your feature request related to a problem? Please describe.**

I am the lead developer of Sqreen's Go agent, and some users are unfortunately experiencing integration issues when using your APMSQL's driver wrapper `tracingDriver` with our SQL-injection protection.

The problem simply comes from the fact the underlying wrapped driver gets hidden and our SQL dialect detection function no longer gets the underlying driver package path but `go.elastic.co/apm/module/apmsql` instead.

**Describe the solution you'd like**

Simply define a new `tracingDriver` method `Unwrap` returning the wrapped driver so that we can detect it and unwrap it:

```
func (d *tracingDriver) Unwrap() driver.Driver {
    return d.Driver
}
```

**Additional context**

As this is a very common issue, I wrote a Go proposal to try to standardize the `Unwrapper` interface at https://github.com/golang/go/issues/42460

**Comment by axw** [comment]
@Julio-Guerra thanks, your proposed solution looks reasonable to me. I'll create a PR shortly.

**Comment by Julio-Guerra** [comment]
> @Julio-Guerra thanks, your proposed solution looks reasonable to me. I'll create a PR shortly.

Glad to read it - ready on my side too ^^
Thanks a lot for the quick response here.
