### ISSUE TITLE
Add support for pgx (the recommended replacement for lib/pq)

### ISSUE THREAD

**Issue by StianOvrevage** [elastic/apm-agent-go#851]
`apm-agent-go` conveniently supports `lib/pq` which we used earlier. `lib/pq` is however now in maintenance mode and the recommended replacement is `pgx`. From https://github.com/lib/pq:

> This package is effectively in maintenance mode and is not actively developed. Small patches and features are only rarely reviewed and merged. We recommend using pgx which is actively maintained.

It would be great with support for `pgx` out of the box in `apm-agent-go`.

There is already a related issue in the `pgx` repo https://github.com/jackc/pgx/issues/652

**Comment by axw** [comment]
@StianOvrevage thanks for opening the issue!

Support for pgx was recently added in https://github.com/elastic/apm-agent-go/pull/831.

Is there still something missing code-wise, or were you under the impression that pgx wasn't supported because it's not mentioned in https://www.elastic.co/guide/en/apm/agent/go/current/supported-tech.html?

I see now that the docs haven't been rebuilt - I'll get that sorted out.

**Comment by StianOvrevage** [comment]
Nice! Yep, it was just from the docs.

You should probably also update https://www.elastic.co/guide/en/apm/agent/go/current/builtin-modules.html#builtin-modules-apmsql with `module/apmsql/pgxv4` in the list :)

**Comment by axw** [comment]
> You should probably also update https://www.elastic.co/guide/en/apm/agent/go/current/builtin-modules.html#builtin-modules-apmsql with module/apmsql/pgxv4 in the list :)

It is in the list now. Your browser may have cached the old docs.

Closing now, thanks for bringing the stale docs to our attention!

**Comment by StianOvrevage** [comment]
Just a quick last question. It looks like it only supports the standard `database/sql` version of `pgx` right? So no support for the "native" `pgx` which supports batching etc?

For typical client-facing APIs there's usually not a need for batching queries, but we like to standardize across multiple systems and some other systems we might need to use for example batching.

**Comment by axw** [comment]
@StianOvrevage that's correct, we only have support for the `database/sql` interface at the moment -- and a GORM dialect, which uses the `database/sql` interface. If you have a need for the native API, then feel free to reopen this and adjust the title/description.
