### ISSUE TITLE
[META 382] Zero-configuration support

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-go#870]
Implement zero-configuration support for the agent as described in: https://github.com/elastic/apm/issues/382

SPEC issue: https://github.com/elastic/apm/issues/401

**Comment by axw** [comment]
The Go agent already has zero-configuration support: `service.name` is set from the process name, and the agent attempts to connect to APM Server on localhost by default. We can't automatically set `service.version` yet. This is tracked by https://github.com/elastic/apm-agent-go/issues/456.

Nothing left to do here (except #456), so closing this out.
