### ISSUE TITLE
[META 408] Instrumentation for AWS S3

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-go#881]
Provide instrumentation for AWS S3.

Meta issue: elastic/apm#408
SPEC: elastic/apm#409

**Comment by stuartnelson3** [comment]
This has been merged with tracing, but I would still like to add some additional metrics (bytes transferred, bytes received, active transfers come immediately to mind, any others?). Should we do that in this issue, or open another one?

**Comment by axw** [comment]
I think we should close this one and open a new one, as we'll probably want to align across agents.
