### ISSUE TITLE
Adding kataras/iris middleware

### ISSUE THREAD

**Issue by fari-99** [elastic/apm-agent-go#891]
**Is your feature request related to a problem? Please describe.**
Currently there is no middleware for framework kataras/iris

**Describe the solution you'd like**
i want someone to create apm module for framework kataras/iris

**Describe alternatives you've considered**
I made a fork, made module apmiris, copy apmgin module and change it so i can run using kataras/iris framework, and i tried it on my app, hey it's working.

**Additional context**
i'm pretty new when contribute on github, so i don't know what i need to do. as i said i just copied apmgin module, change some code so it can run on kataras/iris, i don't know how the test work, so i skip those (i know it's bad habit to do this, but honestly i don't know anything how this works).

here is my attempt to create the new module [apmiris](https://github.com/fari-99/apm-agent-go/tree/master/module/apmiris)

if you have any advice, please tell me.
i'm just a newbie in this contribution world, usually my work don't have those (hahaha, looks good -> merge)

**Comment by axw** [comment]
@fari-99 thank you for opening the issue.

Iris has had a problematic history (see https://www.reddit.com/r/golang/comments/b481q7/a_warning_about_githubcomkatarasiris/, https://github.com/the-benchmarker/web-frameworks/issues/1129, https://github.com/avelino/awesome-go/pull/1135). For this reason, and also the fact that nobody else has been asking for it, we will not be adding any Iris middleware to this repo at this time. I will therefore close the issue.

You can continue to maintain the middleware as an external repo; it does not _need_ to be part of the apm-agent-go repo. The API for the Go agent is stable. If you would like any help using the Go agent's API for developing middleware, please head over to https://discuss.elastic.co/c/apm.

**Comment by fari-99** [comment]
ouch, thank you for your reply @axw . 

LMAO.
