### ISSUE TITLE
StartTransaction sends unnamed transactions that never show up in the UI

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#897]
Sending a transaction with an empty name (e.g. with `apm.DefaultTracer.StartTransaction("", "type").End()`) completes without error, but the transaction is not shown in the APM UI.

When no transaction name is specified, we should set a default such as "(unnamed)".

**Comment by graphaelli** [comment]
Should an ingest pipeline [also] handle this?

**Comment by jalvz** [comment]
There is also https://github.com/elastic/apm-agent-go/issues/704

**Comment by axw** [comment]
Ah, thanks @jalvz. I'll close this as a duplicate.

@graphaelli there's some discussion on https://github.com/elastic/apm-server/issues/3141 about that. IMO we should just require agents to send a non-empty transaction name, and anything else is undefined behaviour. In a later release we should reject such events.
