### ISSUE TITLE
Add Support for storing HTTP Headers (Req & Resp) for gRPC calls

### ISSUE THREAD

**Issue by jpopadak** [elastic/apm-agent-go#900]
**Is your feature request related to a problem? Please describe.**
There does not seem to be any documentation on how view headers from a gRPC request. 

For example, the `Host` gets set for `apmhttp` (See https://github.com/elastic/apm-agent-go/pull/280) but not for `apmgrpc`. Why not, when grpc is over an HTTP2 connection?

**Describe the solution you'd like**
I would love if it could store the [same request headers](https://github.com/elastic/apm-agent-go/blob/6c3b46004fd1b83abc2089fc399739affc48bde2/context.go#L162) and the [same response headers](https://github.com/elastic/apm-agent-go/blob/6c3b46004fd1b83abc2089fc399739affc48bde2/context.go#L225) as `apmhttp` modules does. Thus, its easy to see standard headers from the `apmgrpc` interceptors. Ideality, it should happen in `getIncomingMetadataTraceContext` since it already pulls the Request Metadata.

**Describe alternatives you've considered**
Alternatives include creating our own interceptor that runs after the `apmgrpc` interceptor. It adds the headers to the parent span.

**Additional context**

**Comment by axw** [comment]
Thanks for opening this @jpopadak. I agree, it would be very sensible to include the underlying HTTP-related context.
