### ISSUE TITLE
gRPC Stream Interceptors

### ISSUE THREAD

**Issue by jpopadak** [elastic/apm-agent-go#901]
**Is your feature request related to a problem? Please describe.**
There currently exists within `apmgrpc` [`UnaryClientInterceptor`](https://github.com/elastic/apm-agent-go/blob/master/module/apmgrpc/client.go#L41) and [`UnaryServerInterceptor`](https://github.com/elastic/apm-agent-go/blob/master/module/apmgrpc/server.go#L51). 

I see within the [documentation](https://www.elastic.co/guide/en/apm/agent/go/master/builtin-modules.html#builtin-modules-apmgrpc) it says no Stream support exists for gRPC.
> There is currently no support for intercepting at the stream level. Please file an issue and/or send a pull request if this is something you need.

Well, here I am asking for a Client and Server Stream Interceptor for gRPC use. 🙃 
We have many services that use gRPC Stream APIs, and this is sadly one of our blockers for a quick migration.

**Describe the solution you'd like**
A similar interceptor (just as easy) as the `UnaryClientInterceptor` and `UnaryServerInterceptor`.

**Describe alternatives you've considered**

**Additional context**
Unrelated, but gRPC specific: Would be wonderful if we could also get #900 included.

**Comment by axw** [comment]
What would you expect the stream interceptors to measure? Beginning to end of stream? Anything in between?

**Comment by jpopadak** [comment]
Something like how the Unary interceptors work.
- Timing of each message.
- Deadline if any
- Response code
- Error if any
I dont think we need the whole message body (most people probably wont use it).

The [Logrus interceptor](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/logging/logrus/server_interceptors.go#L56-L75) is a good basic example of how to retrieve the data.

**Comment by axw** [comment]
Thanks @jpopadak. Seems reasonable to create a transaction/span for the entire stream. Maybe in the future we could extend this to log events for individual messages written to and read from the stream, if we implement something like https://github.com/elastic/apm-agent-go/issues/818.

**Comment by jpopadak** [comment]
Yeah, the only thing I worry about is the max number of spans. It might be hit quicker for Stream APIs.
For example, one of our services streams its data using thousands of messages on a "single stream".

**Comment by axw** [comment]
@jpopadak if you have a chance to test this out some time soon I'd appreciate any feedback you may have, so we can make changes before the next release as needed.
