### ISSUE TITLE
[META 424] Public API extended by destination fields

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-go#916]
Extend the public API of the agent to allow setting destination fields as described in https://github.com/elastic/apm/issues/424 .

**Comment by axw** [comment]
This is already done except for cloud region, just need to add that.

**Comment by axw** [comment]
It was just discovered in https://discuss.elastic.co/t/data-validation-error-from-traefik-go-agent-to-elastic-apm-server/267614 that we send destination context even when some fields are unspecified, which leads to a validation error. In this case we should not send the context, as described at https://github.com/elastic/apm/issues/424#issuecomment-799576610
