### ISSUE TITLE
apmot: handle http.host tag

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-go#917]
**Is your feature request related to a problem? Please describe.**

Traefik apparently creates spans with a host-less `http.url` tag, and host is recorded in a separate `http.host` tag. The latter is not part of the OpenTracing semantic conventions, hence we have not been translating it.

**Describe the solution you'd like**

Handle `http.host` as well, and combine it with `http.url`.

**Describe alternatives you've considered**

?

**Additional context**

https://discuss.elastic.co/t/data-validation-error-from-traefik-go-agent-to-elastic-apm-server/267614

**Comment by marclop** [comment]
from what I can see in the payload and log that the user provided, there's an `http_host` but there isn't an `http.host` tag, is there some sort of mutation going on that replaces the `.` with `_`?

```javascript
"resource" [
    {
        "span": {
            "duration": 0.067705,
            "id": "2a4bb5df0ab76f06",
            "name": "forward api@internal/api@internal",
            "timestamp": 1615972480966543,
            "trace_id": "6c6c4a2dc29dc2d4ea7f06006c9a5aef",
            "transaction_id": "6c6c4a2dc29dc2d4",
            "type": "external",
            "context": {
                "destination": {
                    "service": {
                        "type": "external"
                    }
                },
                "http": {
                    "url": "http:///api/overview"
                },
                "tags": {
                    "service_name": "api@internal",
                    "router_name": "api@internal",
                    "http_host": "202.8.174.146:5000",
                    "http_status_code": "200",
                    "span_kind": "client"
                }
            },
            "parent_id": "6c6c4a2dc29dc2d4",
            "stacktrace": [],
            "subtype": "http"
        }
    }
]
```

**Comment by axw** [comment]
> is there some sort of mutation going on that replaces the . with _?

Yes, both in the agent: https://github.com/elastic/apm-agent-go/blob/cac4529af514587225dda5bfef5c6e7f925686b8/utils.go#L53
and in the server: https://github.com/elastic/apm-server/blob/fe9f370189bcddd568e51b74a5fb047288657a15/model/labels.go#L27-L32

(This is to avoid creating hierarchical objects which may lead to mapping conflicts. )

**Comment by marclop** [comment]
Ah, I missed that completely, thanks for pointing it out.
