### ISSUE TITLE
No way to use WithPanicPropagation() when using apmgorilla.Instrument(r)

### ISSUE THREAD

**Issue by mcgrawia** [elastic/apm-agent-go#919]
**Describe the bug**
I am trying to enable WithPanicPropagation() in my application because we have a custom recovery handler. Unfortunately there doesn't seem to be a way to use this setting when instrumenting the applications with `apmgorilla.Instrument(r)`.

Inside the definition of `apmgorilla.MiddlewareI()` there is this code:
```go
        return func(h http.Handler) http.Handler {
		return apmhttp.Wrap(
			h,
			apmhttp.WithTracer(opts.tracer),
			apmhttp.WithServerRequestName(routeRequestName),
			apmhttp.WithServerRequestIgnorer(opts.requestIgnorer),
		)
	}
```

I've also tried modifying this into a new function in my code, but then I would not be able to use the apmgorilla internal `routeRequestName` function.

Additionally, it seems like using `WithRecovery(r RecoveryFunc) ServerOption` could solve the issue, but similarly, I cannot figure out how to set one when using `Instrument`.

Is there a way to enable this that I am missing?

Thanks

**Comment by axw** [comment]
@mcgrawia you're not missing anything, it's just not something that ever got implemented for apmgorilla. https://github.com/elastic/apm-agent-go/pull/920 adds an apmgorilla.WithPanicPropagation option.

**Comment by mcgrawia** [comment]
amazing! thank you for the quick turn around!
