### ISSUE TITLE
Add fasthttp support!

### ISSUE THREAD

**Issue by savsgio** [elastic/apm-agent-go#925]
Do you have any plan to adds support to [fasthttp](https://github.com/valyala/fasthttp)? 
I can see the `apm-agent` only support `net/http`.

Thanks!

**Comment by axw** [comment]
@savsgio not currently - let's use this issue as a feature request. If you are interested, contributions would be welcome.

**Comment by savsgio** [comment]
Hi @axw,

I could try to add support for fasthttp! I will create a PR with that. 😉

**Comment by savsgio** [comment]
Thank you so much @axw! 😉 🎉
