### ISSUE TITLE
Only one SQL was executed, but the span of gormv2 appears multiple？

### ISSUE THREAD

**Issue by eddycjy** [elastic/apm-agent-go#935]
**Describe the bug**
I only executed one SQL in the code, but the span of SQL on kibana appears to be multiple.
- sampleA: ![image](https://user-images.githubusercontent.com/13746731/114701093-f0575100-9d54-11eb-81e0-15b2d6251496.png)
- sampleB: ![image](https://user-images.githubusercontent.com/13746731/114701596-986d1a00-9d55-11eb-9d0f-292b89bd0159.png)

**To Reproduce**
1. app code in grpc server:
![image](https://user-images.githubusercontent.com/13746731/114701816-e124d300-9d55-11eb-966a-68caaa193a8a.png)

2. Request him.
3. See error.

**Expected behavior**
Execute a SQL, only one span should appear.

**Comment by axw** [comment]
If you look at the details of each span in Kibana, is the "action" the same? I expect one will be "prepare" and one will be "exec". That will be because GORM is creating a prepared statement and then executing it.

**Comment by eddycjy** [comment]
> If you look at the details of each span in Kibana, is the "action" the same? I expect one will be "prepare" and one will be "exec". That will be because GORM is creating a prepared statement and then executing it.

@axw Are you referring to such, for example:

1.  Overview: 
![image](https://user-images.githubusercontent.com/13746731/114842912-e3496900-9e0b-11eb-83d3-e44e6d7a4c5d.png)

2.  spanA: 
![image](https://user-images.githubusercontent.com/13746731/114842997-f5c3a280-9e0b-11eb-8f0d-2ce7e2dc483a.png)

3.  spanB:
![image](https://user-images.githubusercontent.com/13746731/114843421-623ea180-9e0c-11eb-9cbb-22173871d984.png)

4. spanC:
![image](https://user-images.githubusercontent.com/13746731/114843780-c2354800-9e0c-11eb-8e6e-31824380ec91.png)

But I have a doubt that there are matters that do not have the full three processes, and this is why？

![image](https://user-images.githubusercontent.com/13746731/114845101-0aa13580-9e0e-11eb-84b8-3f041e810535.png)

No span display for connect events?

**Comment by axw** [comment]
There won't be a connect span in every transaction, as database connections are pooled and reused. In the second screenshot you shared, a database connection would have been reused from an earlier transaction.

> So elastic-apm-go is recording each phase of gormv2 as a span, right?

Yes. The `prepare` phase can take a significant amount of time, so we create a span for that. Obviously we will create a span each time a prepared statement is executed.

The `prepare` and `exec` spans could be combined if there's just one execution, but the agent doesn't know that there will be only one exec. If gorm used `Conn.ExecContext` instead, then we would create just one span.

**Comment by eddycjy** [comment]
> There won't be a connect span in every transaction, as database connections are pooled and reused. In the second screenshot you shared, a database connection would have been reused from an earlier transaction.
> 
> > So elastic-apm-go is recording each phase of gormv2 as a span, right?
> 
> Yes. The `prepare` phase can take a significant amount of time, so we create a span for that. Obviously we will create a span each time a prepared statement is executed.
> 
> The `prepare` and `exec` spans could be combined if there's just one execution, but the agent doesn't know that there will be only one exec. If gorm used `Conn.ExecContext` instead, then we would create just one span.

Mostly understood, thanks @axw .

It is suggested that a proper description could be written at the gormv2 example to avoid confusion.

**Comment by axw** [comment]
> It is suggested that a proper description could be written at the gormv2 example to avoid confusion.

That sounds like a good idea. Thanks @eddycjy! I've opened https://github.com/elastic/apm-agent-go/issues/936 for that
