### ISSUE TITLE
Fiber integration

### ISSUE THREAD

**Issue by th0th** [elastic/apm-agent-go#955]
I was thinking of posting this as a feature request but I decided to go with a question first :)

Do you folks have any plans to add [fiber](https://github.com/gofiber/fiber) integration? 💐

**Comment by axw** [comment]
@th0th we don't have any plans for it at the moment. I see that it is built upon fasthttp, so I think support for fiber would be dependent on https://github.com/elastic/apm-agent-go/issues/925.

Let's use this issue as a feature requests. If you are interested, contributions would be welcome.
