### ISSUE TITLE
Make apmhttp tracecontext headers consistent with W3C spec

### ISSUE THREAD

**Issue by emmakingston** [elastic/apm-agent-go#958]
**Is your feature request related to a problem? Please describe.**
W3C specification for trace-context (traceparent, tracestate) headers says:
> "Vendors MUST expect the header name in any case (upper, lower, mixed), and SHOULD send the header name in lowercase."

Per `apm-agent-go/module/apmhttp/traceheaders.go` and `/handler.go`, the 
(non-apm backwards compatibility) traceparent header is checked with  `W3CTraceparentHeader = "Traceparent"`, and tracestate `TracestateHeader = "Tracestate"`. This is inconsistent with W3C spec as the code only supports Sentence case. 

The [docs](https://www.elastic.co/guide/en/apm/get-started/current/distributed-tracing.html#w3c-tracecontext) say :
>"All Elastic agents now support the official W3C tracecontext spec and traceparent header."  

however as above I'm not sure this is true?

**Describe the solution you'd like**
Add support for at least the header to be in lowercase (the W3C recommendation) and ideally any case for traceparent and tracestate headers. 

I am aware of `func ParseTraceparentHeader(h string)` being accessible - but feel there is value in the default accepting any variation

**Comment by axw** [comment]
@emmakingston thanks for opening the issue!

Did you open this as a theoretical issue, or because you observed that the instrumentation was not properly handling `traceparent` headers?

The Go agent relies on the `net/http` behaviour documented in https://golang.org/pkg/net/http/#Request:

> // For incoming requests, the Host header is promoted to the
> // Request.Host field and removed from the Header map.
> //
> // HTTP defines that header names are case-insensitive. The
> // request parser implements this by using CanonicalHeaderKey,
> // making the first character and any characters following a
> // hyphen uppercase and the rest lowercase.

That is, `net/http` server records request headers in their canonical form. e.g. "tRaCePaReNt" becomes "Traceparent". We then just look for "Traceparent", avoiding the need for (and overhead of) case-insensitive matching.

**Comment by emmakingston** [comment]
Thanks for your quick response @axw, that's reassuring and something I should have done a bit more diligence around first.

You're right that it was theoretical - we were looking to implement some custom stuff using this code as a guideline but without the use of `net/http`, which is how we picked up this (non-)issue. Thanks for taking the time to reply!

**Comment by axw** [comment]
No worries!
