### ISSUE TITLE
Missing tag for module/apmawssdkgo

### ISSUE THREAD

**Issue by mcgrawia** [elastic/apm-agent-go#962]
**Describe the bug**
I am trying to install the apmawssdkgo module, but getting an error `unknown revision module/apmawssdkgo/v1.11.0`. From what I can tell, all the other sub-modules have git tags of the form `module/<sub-module>/<version>` but there does not seem to be a tag for the `apmawssdkgo` sub-module. I think this tag is required to install the AWS APM module.

**Comment by jalvz** [comment]
@mcgrawia `apmawssdkgo` was added in v1.12.0, which is *just* released.
Please try that version, and if that doesn't work feel free to re-open the issue.

**Comment by mcgrawia** [comment]
thanks @jalvz. v1.12.0 did the trick
