### ISSUE TITLE
Add support for go-restful v3

### ISSUE THREAD

**Issue by luqmansen** [elastic/apm-agent-go#967]
As the title said, is there any plan to add support for the current [go-restful v3](https://github.com/emicklei/go-restful/tree/v3)
 
Currently apmrestful only support until go-restful v2, adding this support would be great, thank you

**Comment by axw** [comment]
@luqmansen thanks for opening the issue! This isn't currently planned, but it's certainly a reasonable request. If you would like to contribute then we'd be happy to review PRs. Otherwise, it's now in the backlog.

**Comment by luqmansen** [comment]
Opened a PR, can you please review it? Thank you @axw

**Comment by axw** [comment]
Closed by #968 :tada:
