### ISSUE TITLE
apm.Context.SetHTTPRequest wipes c.user.Username set manually

### ISSUE THREAD

**Issue by mcgrawia** [elastic/apm-agent-go#970]
**Describe the bug**
In my application, I am manually calling `apm.Context.SetUsername` to add user info to the transaction. When the transaction is set to the APM server, the `username` is wiped from the data in `SetHTTPRequest`. I've traced the problem to the following lines, which don't take into account when `c.user.Username` is already set:
https://github.com/elastic/apm-agent-go/blob/master/context.go#L206-L213
```go
	username, _, ok := req.BasicAuth()
	if !ok && req.URL.User != nil {
		username = req.URL.User.Username()
	}
	c.user.Username = truncateString(username)
	if c.user.Username != "" {
		c.model.User = &c.user
	}
```

It seems like this line: `c.user.Username = truncateString(username)` sets both `c.user.Username` and `c.model.User.Username` since they point to the same `model.User` object.

**To Reproduce**
1. In your http application, call `tx.Context.SetUsername(username)`
2. observe no username is present in the APM events

**Expected behavior**
Username should be set in the APM events.

**Comment by axw** [comment]
Thanks for the report @mcgrawia! I'll get onto a fix shortly.

**Comment by mcgrawia** [comment]
thanks for the quick fix @axw! the change works great.
