### ISSUE TITLE
deps ensure fails

### ISSUE THREAD

**Issue by JayKakadiya** [elastic/apm-agent-go#980]
deps ensure is failing with below error.
error while writing out vendor tree: failed to write dep tree: failed to export howett.net/plist: unable to deduce repository and source type for "gitlab.howett.net/go/plist": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://gitlab.howett.net/go/plist?go-get=1": Get http://gitlab.howett.net/go/plist?go-get=1: dial tcp: lookup gitlab.howett.net: no such host

**Comment by simitt** [comment]
This looks like an issue with https://gitlab.howett.net/go/plist - can you follow up there?
Generally, is it feasible for you to switch to modules, given that go dep is deprecated?

**Comment by axw** [comment]
I don't think there is anything wrong with the Go Agent here, so I'll close. If you continue to have issues, please open a topic at https://discuss.elastic.co/c/apm and we'll see what we can do.
