### ISSUE TITLE
apmhttp.WithClientTrace() can probably panic, for example r.TLS.End()

### ISSUE THREAD

**Issue by lufishggg** [elastic/apm-agent-go#981]
**Describe the bug**
apmhttp.WithClientTrace() can probably panic due to nil pointer.

**To Reproduce**
Can check go net/http/transport.go, trace.TLSHandshakeDone and trace.TLSHandshakeDone are not executed at one goroutine. If run TLSHandshakeDone before TLSHandshakeStart, it will panic. See go.elastic.co/apm/module/apmhttp@v1.9.0/clienttrace.go:84

**Expected behavior**
before r.TLS.End(), should check if span is null

**Comment by simitt** [comment]
`TLSHandshakeDone` is only called if `TLSHandshakeStart` was called, I don't expect any nil pointer panics with the current code and an additional nil check should not be required.

@lufishggg did you run into any concrete issues?

**Comment by axw** [comment]
As above, TLSHandshakeDone is only called after TLSHandshakeStart is called, so it would be illogical to add a nil pointer check. If you have observed panics in your application, please reopen with steps to reproduce the issue.

**Comment by lufishggg** [comment]
![image](https://user-images.githubusercontent.com/31639618/126299979-f6c0b08d-19e0-407d-b6c4-e328666152c2.png)

TLSHandshakeStart is run at another goroutine, which means that TLSHandshakeDone may be called before TLSHandshakeStart is called @simitt

**Comment by axw** [comment]
The fact that it's in a different goroutine isn't particularly important seeing as TLSHandshakeDone doesn't get invoked until after `<-errc` in this code:

https://github.com/golang/go/blob/9e26569293c13974d210fd588ebfd29b857d8525/src/net/http/transport.go#L1525-L1546

However, you are still correct: it is possible for an error to be sent to `errc` if the TLSHandshakeTimeout elapses, in which case TLSHandshakeStart may not have been called. Thanks for raising the issue.
